window.MIDAD_CONFIG={supabaseUrl:"https://froegigfmpmvtecztfbf.supabase.co",controlRoomFunction:"/functions/v1/midad_control_room",dashboardAction:"dashboard",buildVersion:"v6-explainable-2026-09-23",emergencyTargetUsd:1000,knownRuntimeSnapshot:{incidents:[{severity:"critical",title:"n8n execution quota",detail:"Execution capacity is a known runtime dependency.",source:"n8n"},{severity:"warning",title:"Agent credit dependency",detail:"Some agent actions depend on provider credits.",source:"OpenRouter"}],workflows:[{name:"Revenue Intelligence Scanner v2",id:"fChZsDbnsxP9dwwr"},{name:"Opportunity Intelligence Mesh v1",id:"5EqjQcaY0dq8SHTA"},{name:"Market Intelligence & New Assets v1",id:"h9IOP39SuVYaXnDP"},{name:"Intelligence Read v1",id:"4aBQunkIwgkwgfki"},{name:"AI Command Core v2",id:"LC3tTcFBEukB1R5u"}],agents:[{name:"Telegram Control Room Live",lifecycle:"published"},{name:"Telegram Control Room Agent",lifecycle:"published"},{name:"Financial Intelligence & Capital Agent v1",lifecycle:"draft"},{name:"Emergency Revenue Hunter v1",lifecycle:"draft"},{name:"Revenue & Outreach Copilot v1",lifecycle:"draft"}]}};

(()=>{"use strict";
var C=window.MIDAD_CONFIG,A=document.getElementById("app"),TG=function(){return window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null};
var I={dashboard:"◈",digital:"◫",mission:"✦",automation:"⌁",trading:"↗",clients:"◎",terminal:"⌘",opportunities:"⌁",revenue:"◆",capital:"◌",wallets:"◇",mining:"⛏",intelligence:"⌬",alerts:"◍",personal:"●",settings:"⚙",health:"✺"};
var R=[["dashboard","الرئيسية","NEURAL INDEX"],["digital","لوحة الحالة الرقمية","DIGITAL DASHBOARD"],["mission","غرفة المهمة","MISSION"],["automation","الأتمتة والمهام","TASK MATRIX"],["trading","التداول المحاكى","PAPER TERMINAL"],["clients","العملاء ومساحات العمل","WORKSPACE HUB"],["terminal","الطرفية والسجلات","LIVE TERMINAL"],["opportunities","الفرص","OPPORTUNITY INTELLIGENCE"],["revenue","الإيرادات","REVENUE"],["capital","رأس المال","CAPITAL"],["wallets","المحافظ","WALLETS"],["mining","التعدين","MINING"],["intelligence","الذكاء وOSINT","OSINT"],["alerts","التنبيهات","ALERT ENGINE"],["personal","المساحة الشخصية","PRIVATE"],["settings","الإعدادات","CONTROL"],["health","صحة النظام","HEALTH"]];
var G=[["COMMAND",["dashboard","digital","mission","automation","terminal"]],["MARKETS",["trading","opportunities","intelligence"]],["REVENUE",["revenue","clients"]],["CAPITAL",["capital","wallets","mining"]],["SYSTEM",["alerts","personal","settings","health"]]];
function safeStorageJSON(key,fallback){
  try{
    var raw=localStorage.getItem(key);
    return raw?JSON.parse(raw):fallback;
  }catch(e){
    try{localStorage.removeItem(key)}catch(_){}
    return fallback;
  }
}
var S={
  route:(location.hash||"#dashboard").slice(1),
  connected:false,
  label:"DEGRADED / AWAITING VERIFY",
  live:null,
  user:{},
  logs:[],
  accessKey:"",
  sessionToken:"",
  modules:safeStorageJSON("midad_ui_modules",["neural","metrics","market","activity","health","quick"]),
  personal:safeStorageJSON("midad_personal",{"income":[],"wallets":[],"trades":[],"clients":[],"notes":""})
};
if(!R.some(function(x){return x[0]===S.route}))S.route="dashboard";
var $=function(s){return document.querySelector(s)},esc=function(v){return String(v==null?"":v).replace(/[&<>"']/g,function(m){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]})};
var num=function(v){return v==null||v===""?"—":Number(v).toLocaleString("en-US",{maximumFractionDigits:2})};
var money=function(v){return v==null?"—":"$"+Number(v||0).toLocaleString("en-US",{maximumFractionDigits:2})};
var meta=function(id){return R.find(function(x){return x[0]===id})||R[0]};
var pill=function(t,c){return '<span class="pill '+(c||"blue")+'">'+esc(t)+'</span>'};
var card=function(t,e,b,c){return '<section class="card '+(c||"")+'"><div class="card-head"><div><div class="eyebrow">'+esc(e)+'</div><div class="card-title">'+esc(t)+'</div></div></div>'+b+'</section>'};
function save(){localStorage.setItem("midad_personal",JSON.stringify(S.personal))}
function toast(m,c){var st=$("#toastStack");if(!st)return;var d=document.createElement("div");d.className="toast "+(c||"good");d.textContent=m;st.appendChild(d);setTimeout(function(){d.remove()},4200)}
function log(m,t){S.logs.unshift({t:new Date().toLocaleTimeString("en-GB"),msg:m,type:t||"info"});S.logs=S.logs.slice(0,70);var b=$("#consoleBody");if(b)b.innerHTML=logs()}
function logs(){return(S.logs.length?S.logs:[{t:new Date().toLocaleTimeString("en-GB"),msg:"MIDAD Neural UI initialized",type:"ok"}]).map(function(x){return '<div class="log '+esc(x.type)+'">['+esc(x.t)+'] '+esc(x.msg)+'</div>'}).join("")}
function title(t,s,a){return '<div class="hero"><div><div class="kicker"><span class="dot '+(S.connected?"live":"")+'"></span><span>MIDAD OS // '+esc(meta(S.route)[2])+'</span><span>•</span><span>'+(S.connected?"VERIFIED SESSION":"DEGRADED / AWAITING VERIFY")+'</span></div><h1>'+esc(t)+'</h1><p>'+esc(s)+'</p></div><div class="hero-actions">'+(a||"")+"</div></div>"}
function nav(){return G.map(function(g){return '<div class="nav-section"><div class="nav-label">'+g[0]+'</div>'+g[1].map(function(id){var r=meta(id);return '<button class="nav-item '+(S.route===id?"active":"")+'" data-route="'+id+'"><span class="nav-ico">'+I[id]+'</span><span class="nav-name">'+esc(r[1])+'</span><span class="nav-meta">'+esc(r[2])+'</span></button>'}).join("")+'</div>'}).join("")}
function shell(){var r=meta(S.route);A.innerHTML='<aside class="sidebar" id="sidebar"><div class="logo"><div class="logo-mark">M</div><div><strong>MIDAD</strong><span>NEURAL COMMAND CENTER</span></div></div>'+nav()+'<div class="side-foot"><div class="side-state"><span class="dot '+(S.connected?"live":"")+'"></span><span>'+esc(S.label)+'</span></div><div class="sub" style="margin-top:7px">لا أرقام حية بلا تحقق من المصدر.</div></div></aside><header class="topbar"><div class="top-left"><button class="icon-btn" data-action="menu">☰</button><div class="brand-mini">MIDAD</div><div class="crumb"><strong>'+esc(r[1])+'</strong><span>'+esc(r[2])+'</span></div></div><div class="top-right"><button class="icon-btn" data-action="command">⌘K</button><button class="icon-btn" data-action="needs">◍</button><div class="identity"><div class="avatar">'+esc((S.user.name||S.user.telegram||"M").slice(0,1).toUpperCase())+'</div><div><b style="font-size:11px">'+esc(S.user.name||S.user.telegram||"MIDAD User")+'</b><small>'+(S.connected?"Connected / Verified":"Awaiting secure context")+'</small></div></div></div></header><main class="main"><section class="route active">'+routeView()+'</section></main><nav class="mobile-nav">'+["dashboard","automation","trading","terminal"].map(function(id){return '<button class="'+(S.route===id?"active":"")+'" data-route="'+id+'"><span class="mi">'+I[id]+"</span>"+esc(meta(id)[1])+"</button>"}).join("")+'<button data-action="menu"><span class="mi">☰</span>المزيد</button></nav><div class="command" id="command"><div class="cmd-box"><input class="cmd-input" id="cmdInput" placeholder="ابحث عن صفحة أو أمر…  Ctrl / Cmd + K"><div class="cmd-list" id="cmdList"></div></div></div><div class="drawer" id="drawer"><div class="drawer-head"><div><b>WHAT NEEDS ME?</b><div class="sub">الموافقات والحالات التي تحتاج تدخلك</div></div><button class="icon-btn" data-action="needs">×</button></div><div class="drawer-body">'+needs()+'</div></div><div class="modal" id="modal"><div class="modal-box" id="modalBox"></div></div><div class="toast-stack" id="toastStack"></div>'}
function routeView(){var f={dashboard:dash,digital:digitalDashboard,mission:mission,automation:automation,trading:trading,clients:clients,terminal:terminal,opportunities:opportunities,revenue:revenue,capital:capital,wallets:wallets,mining:mining,intelligence:intel,alerts:alerts,personal:personal,settings:settings,health:health};return(f[S.route]||dash)()}
function stats(){var h=(S.live&&S.live.health)||S.live||{};var inc=(S.personal.income||[]).reduce(function(a,x){return a+Number(x.amount||0)},0);return{signals:Number(h.signals||0),opps:Number(h.opportunities||0),alerts:Number(h.sentinel_alerts||0)+Number(h.derived_alerts||0),runs:Number(h.engine_runs||0),clients:Number(h.clients||0),approvals:Number(h.pending_approvals||0),income:inc}}
function dash(){return title("Neural Command Index","القيادة السينمائية لمجريات النظام: النبض، القرار، التدفق، المال، والمخاطر.",'<button class="btn primary" data-action="connect">⚡ Verify</button><button class="btn" data-action="terminal">⌘ Terminal</button>')+'<div class="command-bar"><button class="chip primary" data-action="scan">⌁ Neural Scan</button><button class="chip" data-action="opportunityScan">＋ Opportunity</button><button class="chip" data-action="mining">⛏ Mining</button><button class="chip" data-action="autonomy">◎ Autonomy</button><button class="chip" data-route="trading">TRADING</button><button class="chip" data-route="clients">WORKSPACE</button><span style="flex:1"></span>'+pill(S.connected?"LIVE VERIFIED":"DEGRADED",S.connected?"green":"amber")+'</div><div id="dashModules" class="grid g3"></div>'}
function module(id){var d=stats(),target=C.emergencyTargetUsd||1000;
if(id==="neural")return card("Neural Workflow","LIVE ORCHESTRATION",'<div class="node-canvas"><svg viewBox="0 0 800 260"><defs><linearGradient id="f1"><stop stop-color="#5be7d9"/><stop offset="1" stop-color="#9b8cff"/></linearGradient></defs><path class="flow" d="M85 130H230M330 130H470M570 130H715" stroke="url(#f1)"/><rect class="node live" x="35" y="92" width="145" height="76" rx="16"/><rect class="node live" x="230" y="92" width="145" height="76" rx="16"/><rect class="node" x="470" y="92" width="145" height="76" rx="16"/><rect class="node" x="665" y="92" width="100" height="76" rx="16"/><text x="107" y="122" text-anchor="middle">SIGNALS</text><text x="107" y="142" text-anchor="middle">OSINT / EVENTS</text><text x="302" y="122" text-anchor="middle">EVIDENCE</text><text x="302" y="142" text-anchor="middle">VERIFY / SCORE</text><text x="542" y="122" text-anchor="middle">DECISION</text><text x="542" y="142" text-anchor="middle">RISK / VALUE</text><text x="715" y="122" text-anchor="middle">ACTION</text><text x="715" y="142" text-anchor="middle">EXECUTE / VERIFY</text></svg></div><div class="sub" style="margin-top:8px">اسحب الوحدات لإعادة ترتيبها. العقد الحساسة تبقى خلف policy + human approval.</div>'); 
if(id==="metrics")return card("Command Telemetry","SYSTEM PULSE",'<div class="stat-grid"><div class="micro-stat"><b>'+num(d.signals)+'</b><span>signals</span></div><div class="micro-stat"><b>'+num(d.opps)+'</b><span>opportunities</span></div><div class="micro-stat"><b>'+num(d.approvals)+'</b><span>approvals</span></div></div><div class="stat-grid" style="margin-top:8px"><div class="micro-stat"><b>'+num(d.clients)+'</b><span>clients</span></div><div class="micro-stat"><b>'+num(d.runs)+'</b><span>engine runs</span></div><div class="micro-stat"><b>'+num(d.alerts)+'</b><span>alerts</span></div></div><div style="margin-top:12px"><div class="sub">Emergency cashflow</div><div class="metric-row"><div class="metric">'+money(d.income)+'</div><span class="mono sub">/'+money(target)+'</span></div><div class="progress" style="margin-top:8px"><span style="width:'+Math.min(100,d.income/target*100)+'%"></span></div></div>');
if(id==="market")return card("Market Pulse","PAPER / OBSERVE",spark());
if(id==="activity")return card("Activity Stream","AUDIT",'<div class="stack">'+(S.logs.length?S.logs:S.logs).slice(0,5).map(function(x){return '<div class="rowbox"><div class="row-main"><b>'+esc(x.msg)+'</b><small class="mono">'+esc(x.t)+'</small></div>'+pill(x.type==="ok"?"OK":"EVENT",x.type==="ok"?"green":"blue")+'</div>'}).join("")+'</div>');
if(id==="health")return card("System Health","VERIFIED STATE",miniHealth());
return card("Rapid Actions","COMMAND DECK",'<div class="command-bar"><button class="chip primary" data-action="scan">⌁ Scan</button><button class="chip" data-action="opportunityScan">＋ Opportunity</button><button class="chip" data-action="mining">⛏ Mining</button><button class="chip" data-action="autonomy">◎ Autonomy</button></div>');
}
function inject(){var h=$("#dashModules");if(!h)return;h.innerHTML=S.modules.map(function(id){return '<div class="module" draggable="true" data-module="'+id+'" style="'+(id==="neural"||id==="quick"?"grid-column:span 2;":"")+'">'+module(id)+'</div>'}).join("");h.querySelectorAll(".module").forEach(function(el){el.addEventListener("dragstart",function(){el.classList.add("dragging")});el.addEventListener("dragover",function(e){e.preventDefault();el.classList.add("drop-target")});el.addEventListener("dragleave",function(){el.classList.remove("drop-target")});el.addEventListener("drop",function(e){e.preventDefault();var d=h.querySelector(".dragging");if(d&&d!==el){var a=[].indexOf.call(h.children,d),b=[].indexOf.call(h.children,el);if(a<b)h.insertBefore(d,el.nextSibling);else h.insertBefore(d,el)}el.classList.remove("drop-target")});el.addEventListener("dragend",function(){el.classList.remove("dragging");S.modules=[].slice.call(h.children).map(function(x){return x.dataset.module});localStorage.setItem("midad_ui_modules",JSON.stringify(S.modules))})})}
function spark(){return '<div class="spark-wrap"><svg viewBox="0 0 100 120" preserveAspectRatio="none"><defs><linearGradient id="sf"><stop stop-color="#5be7d9" stop-opacity=".3"/><stop offset="1" stop-color="#5be7d9" stop-opacity="0"/></linearGradient></defs><path class="spark-grid" d="M0 20H100M0 60H100M0 100H100"/><polyline class="spark-line" points="0,82 8,76 16,79 24,66 32,70 40,57 48,61 56,53 64,59 72,45 80,50 88,36 100,28"/><polygon class="spark-fill" points="0,82 8,76 16,79 24,66 32,70 40,57 48,61 56,53 64,59 72,45 80,50 88,36 100,28 100,120 0,120" fill="url(#sf)"/></svg></div><div class="metric-row"><div><div class="metric metric-sm">PAPER WATCH</div><div class="sub">no live orders</div></div>'+pill("OBSERVE","blue")+'</div>'}
function miniHealth(){return '<div class="stack">'+["Supabase","n8n","Telegram","Vespa","TinyFish","GitHub"].map(function(x){return '<div class="rowbox"><div class="row-main"><b>'+x+'</b><small>operational channel</small></div>'+pill(x==="Supabase"&&S.connected?"VERIFIED":"UNVERIFIED",x==="Supabase"&&S.connected?"green":"amber")+'</div>'}).join("")+'</div>'}

function digitalDashboard(){
  var d=stats(), h=(S.live&&S.live.health)||{}, live=!!S.connected;
  var truth=live?"VERIFIED BACKEND CONTEXT":"UNVERIFIED / AWAITING VERIFY";
  var atlas=[
    ["الرئيسية","النبض التنفيذي","تلخيص الحالة، المقاييس، التدفق، والتنبيهات السريعة.","signals → telemetry → actions"],
    ["لوحة الحالة الرقمية","الفهم والشفافية","خريطة تشغيلية تشرح الحالة، المصادر، الآليات، والحدود.","state → provenance → mechanics"],
    ["غرفة المهمة","إدارة الأولويات","ما يحدث الآن، ما يلي، ما ينتظر، وما هو محجوب.","now → next → waiting → blocked"],
    ["الأتمتة والمهام","تنسيق التنفيذ","الوكلاء، الـworkflows، طوابير التشغيل، وبوابات الموافقة.","queue → run → verify → execute"],
    ["التداول المحاكى","اختبار الفرضيات","مراقبة وتحليل Paper فقط دون أوامر مالية حية من الواجهة.","observe → hypothesis → paper ledger"],
    ["الفرص","Opportunity Intelligence","تجميع الفرص ومراحلها ومصدرها وطريقة الدفع والثقة.","signal → qualify → negotiate"],
    ["الذكاء وOSINT","قراءة الأدلة","الإشارة، المصدر، البصمة، الدرجة، والثقة.","signal → evidence → confidence"],
    ["الإيرادات","Revenue Engine","تحويل الفرص إلى عروض ومراحل تحصيل واضحة.","prospect → offer → collect"],
    ["رأس المال","Capital Command","السيولة والمصادر والتكاليف وحدود المخاطر.","source → cost → runway → guardrail"],
    ["المحافظ","Wallet Control","فصل العناوين الشخصية عن التشغيلية مع منع الأسرار الحساسة.","address-only → isolated"],
    ["التعدين","Mining Command","قراءة مسار التعدين كمصدر رأس مال مستقل.","pool → workers → hashrate"],
    ["التنبيهات","Alert Engine","الخطورة، المصدر، حداثة البيانات، وحالة التسليم.","severity → source → delivery"],
    ["المساحة الشخصية","Private Workspace","سجل محلي منفصل للدخل والملاحظات والعملاء والتجارب.","local-only records"],
    ["الإعدادات","Control","الاتصال، الحواجز، والهوية البصرية المحلية.","session → visual profile"],
    ["صحة النظام","Health","تمييز verified / degraded / unverified دون ادعاء نجاح.","probe → status → evidence"]
  ];
  var flow=[
    ["01","SIGNAL","إشارة أو حدث يدخل المنظومة","OSINT / event / manual input"],
    ["02","EVIDENCE","تطبيع، بصمة، مصدر، وحداثة","normalize / fingerprint / verify"],
    ["03","DECISION","قيمة + ثقة + مخاطرة","score / risk / policy"],
    ["04","ACTION","تنفيذ مراقب أو طلب موافقة","workflow / human gate"],
    ["05","OUTCOME","قياس النتيجة والتعلم","outcome / feedback loop"]
  ];
  var mechanics=[
    ["محرك الحقيقة","Truth Layer","لا تُعامل الأرقام على أنها حية إلا بعد تحقق المصدر. الحالة الحالية: "+truth+"."],
    ["محرك التنسيق","Orchestrator","يربط الإشارات بالـworkflows والوكلاء بدل ربط الواجهة بمزود واحد."],
    ["بوابة المخاطر","Policy Gate","الأفعال الحساسة تبقى خلف موافقة بشرية؛ التداول الحي مفصول عن واجهة Paper."],
    ["طبقة رأس المال","Capital Layer","تفصل بين الدخل المحلي، التعدين، الفرص، التكاليف، والسيولة."],
    ["حلقة التعلم","Outcome Loop","النتيجة لا تُعد نجاحًا لمجرد التنفيذ؛ يجب تسجيل outcome لإعادة التقييم."],
    ["طبقة الواجهة","Control Surface","Telegram / WebApp / صفحات الويب أدوات تحكم قابلة للاستبدال فوق النواة."]
  ];
  var statusRows=[
    ["Backend session",live?"VERIFIED":"WAITING","مصدر مباشر عند نجاح الاتصال","backend",live?"green":"amber"],
    ["Telemetry",live?"LIVE PAYLOAD":"NO LIVE PROBE","أرقام النظام من payload الحالي فقط","backend",live?"green":"amber"],
    ["Workflow inventory","SNAPSHOT","تعريفات معروفة في runtime snapshot المحلي","snapshot","blue"],
    ["Personal records","LOCAL ONLY","دخل وملاحظات ومحافظ وتجارب مخزنة في المتصفح","local","blue"],
    ["Sensitive execution","HUMAN GATED","الأعمال المالية/التدميرية لا تتجاوز الحاجز تلقائيًا","policy","green"],
    ["Provider availability","DEPENDENCY","n8n / credits / providers قد يحدون التنفيذ","dependency","amber"]
  ];
  return title("Digital Dashboard","الطبقة التي تشرح MIDAD لنفسه وللمستخدم: ماذا لدينا، ماذا يحدث، لماذا، ومن أين جاءت كل معلومة.",'<button class="btn primary" data-action="connect">⚡ Verify Truth</button><button class="btn" data-action="refresh">↻ Refresh</button><button class="btn" data-route="health">✺ Health</button>')+
  '<div class="digital-banner"><div><div class="eyebrow">MIDAD DIGITAL TWIN / EXPLAINABLE CONTROL SURFACE</div><h2>افهم النظام قبل أن تطلب منه أن يتحرك.</h2><p>هذه الصفحة لا تستبدل غرفة التحكم؛ إنها طبقة رؤية فوقها: الحالة، المصدر، الآلية، الحدود، وما يحتاج قرارًا بشريًا.</p></div><div class="digital-truth"><span class="dot '+(live?"live":"")+'"></span><b>'+esc(truth)+'</b><small>'+esc(live?"session token established":"no verified session in browser")+'</small></div></div>'+
  '<div class="digital-legend"><span class="digital-legend-title">DATA PROVENANCE</span><span class="digital-key verified">VERIFIED · من المصدر الحالي</span><span class="digital-key snapshot">SNAPSHOT · تعريف معروف وليس قياسًا حيًا</span><span class="digital-key local">LOCAL · هذا الجهاز فقط</span><span class="digital-key gated">GATED · يتطلب policy / human approval</span></div>'+
  '<div class="grid g4 digital-kpi-grid">'+
    card("System State","CURRENT",'<div class="metric metric-sm">'+esc(live?"VERIFIED":"DEGRADED")+'</div><div class="sub">'+esc(truth)+'</div>')+
    card("Signals","TELEMETRY",'<div class="metric">'+num(d.signals)+'</div><div class="sub">من payload الحالي فقط</div>')+
    card("Opportunities","TELEMETRY",'<div class="metric">'+num(d.opps)+'</div><div class="sub">مخرجات Opportunity Intelligence</div>')+
    card("Human Attention","CONTROL GATE",'<div class="metric">'+num(d.approvals)+'</div><div class="sub">approval records in current payload</div>')+
  '</div>'+
  '<section class="card digital-spine-card"><div class="card-head"><div><div class="eyebrow">OPERATING SPINE</div><div class="card-title">كيف تتحول الإشارة إلى فعل</div></div>'+pill("EXPLAINABLE","green")+'</div><div class="digital-spine">'+flow.map(function(x,i){return '<div class="digital-stage"><div class="digital-stage-top"><span>'+x[0]+'</span><i>'+ (i===flow.length-1?"◎":"→") +'</i></div><b>'+x[1]+'</b><p>'+x[2]+'</p><small>'+x[3]+'</small></div>'}).join("")+'</div></section>'+
  '<div class="grid g2 digital-main-grid">'+
    card("System Map","ARCHITECTURE",'<div class="digital-map"><div class="digital-layer source"><b>INPUTS</b><span>OSINT · Mining · Webhooks · Manual</span></div><div class="digital-connector">↓ normalize / fingerprint</div><div class="digital-layer evidence"><b>EVIDENCE</b><span>source · freshness · reliability · context</span></div><div class="digital-connector">↓ score / policy</div><div class="digital-layer decision"><b>INTELLIGENCE</b><span>value · confidence · risk · priority</span></div><div class="digital-connector">↓ gated execution</div><div class="digital-layer action"><b>ACTION</b><span>n8n · agents · Telegram · human approval</span></div><div class="digital-connector">↓ measure</div><div class="digital-layer outcome"><b>OUTCOME</b><span>result · cost · ROI · feedback</span></div></div>')+
    card("Truth Ledger","PROVENANCE",'<div class="stack">'+statusRows.map(function(x){return '<div class="digital-status-row"><div class="row-main"><b>'+esc(x[0])+'</b><small>'+esc(x[2])+'</small></div><span class="digital-source-badge '+esc(x[4])+'">'+esc(x[1])+'</span></div>'}).join("")+'</div>')+
  '</div>'+
  '<section class="card digital-mechanics"><div class="card-head"><div><div class="eyebrow">MECHANISM ATLAS</div><div class="card-title">ماذا يفعل كل محرك داخل MIDAD؟</div></div><span class="pill blue">TRANSPARENT BY DESIGN</span></div><div class="grid g3">'+mechanics.map(function(x){return '<details class="digital-detail"><summary><span><b>'+esc(x[0])+'</b><small>'+esc(x[1])+'</small></span><i>＋</i></summary><p>'+esc(x[2])+'</p></details>'}).join("")+'</div></section>'+
  '<section class="card digital-ai-guide"><div class="card-head"><div><div class="eyebrow">AI GUIDANCE LENS</div><div class="card-title">ماذا يقترح الذكاء، ومتى يتوقف؟</div></div><span class="pill blue">GUIDANCE ≠ BLIND AUTONOMY</span></div><div class="digital-guidance-grid"><div><b>OBSERVE</b><span>اجمع الإشارة من المصادر المتصلة.</span></div><div><b>VERIFY</b><span>اختبر المصدر والحداثة والبصمة.</span></div><div><b>PRIORITIZE</b><span>رتّب القيمة والثقة والمخاطرة.</span></div><div><b>ASK</b><span>ارفع القرار للبشر عندما تكون الحساسية عالية.</span></div><div><b>EXECUTE</b><span>نفّذ عبر workflow أو agent ضمن policy.</span></div><div><b>LEARN</b><span>سجّل outcome بدل افتراض النجاح.</span></div></div></section>'+
  '<section class="card"><div class="card-head"><div><div class="eyebrow">SECTION ATLAS</div><div class="card-title">خريطة أقسام الواجهة: المدخل → الآلية → المخرج</div></div></div><div class="table-wrap"><table class="table digital-atlas"><thead><tr><th>Section</th><th>Purpose</th><th>Mechanism</th><th>Output</th></tr></thead><tbody>'+atlas.map(function(x){return '<tr><td><b>'+esc(x[0])+'</b></td><td>'+esc(x[1])+'</td><td>'+esc(x[2])+'</td><td><span class="tag">'+esc(x[3])+'</span></td></tr>'}).join("")+'</tbody></table></div></section>'+
  '<div class="digital-next"><div><div class="eyebrow">NEXT BEST ACTIONS / USER CONTROL</div><b>ابدأ من الحقيقة → ثم افهم التدفق → ثم فعّل ما تحتاجه فقط.</b><span>هذه الطبقة لا تنفّذ المال أو التداول الحي؛ هي خريطة القرار والقدرات قبل التنفيذ.</span></div><div class="digital-next-actions"><button class="btn primary" data-route="intelligence">⌬ Inspect Intelligence</button><button class="btn" data-route="automation">⌁ Inspect Automation</button><button class="btn" data-route="capital">◌ Inspect Capital</button></div></div>';
}
function mission(){return title("Mission Control","الآن، التالي، المنتظر، المحجوب — بصرياً وبشكل تشغيلي.",'<button class="btn primary" data-action="scan">⚡ Mission Scan</button><button class="btn" data-action="needs">◍ Needs Me</button>')+'<div class="matrix"><div class="lane"><div class="lane-head"><span>NOW</span><strong>الآن</strong></div><div class="task"><div class="task-line"><i class="task-dot green"></i><b>Verify truth sources</b></div><small>source → freshness → reliability</small></div><div class="task"><div class="task-line"><i class="task-dot"></i><b>Cashflow first</b></div><small>small offer → milestone</small></div></div><div class="lane"><div class="lane-head"><span>NEXT</span><strong>التالي</strong></div><div class="task"><div class="task-line"><i class="task-dot"></i><b>Qualified lead engine</b></div><small>prospect → evidence</small></div><div class="task"><div class="task-line"><i class="task-dot green"></i><b>Feedback loop</b></div><small>response → learn</small></div></div><div class="lane"><div class="lane-head"><span>WAITING</span><strong>منتظر</strong></div><div class="task"><div class="task-line"><i class="task-dot"></i><b>Buyer response</b></div><small>external dependency</small></div><div class="task"><div class="task-line"><i class="task-dot"></i><b>Provider runtime</b></div><small>credits / capacity</small></div></div><div class="lane"><div class="lane-head"><span>BLOCKED</span><strong>محجوب</strong></div><div class="task"><div class="task-line"><i class="task-dot red"></i><b>Live financial execution</b></div><small>human approval + backend</small></div><div class="task"><div class="task-line"><i class="task-dot red"></i><b>n8n quota</b></div><small>runtime dependency</small></div></div></div>'}
function automation(){return title("Automation & Task Matrix","وكلاء + workflows + execution lanes + approval gates.",'<button class="btn primary" data-action="autonomy">◎ Run Autonomy</button><button class="btn" data-action="refresh">↻ Refresh</button>')+'<div class="grid g2">'+card("Agents","AI AGENTS",'<div class="stack">'+C.knownRuntimeSnapshot.agents.map(function(a){return '<div class="rowbox"><div class="row-main"><b>'+esc(a.name)+'</b><small>'+esc(a.lifecycle)+'</small></div>'+pill(a.lifecycle==="published"?"READY":"DRAFT",a.lifecycle==="published"?"green":"amber")+'</div>'}).join("")+'</div>')+card("Workflows","N8N",'<div class="stack">'+C.knownRuntimeSnapshot.workflows.map(function(w){return '<div class="rowbox"><div class="row-main"><b>'+esc(w.name)+'</b><small class="mono">'+esc(w.id)+'</small></div>'+pill("CONFIGURED","blue")+'</div>'}).join("")+'</div>')+'</div><div class="card" style="margin-top:12px"><div class="matrix"><div class="lane"><div class="lane-head"><span>QUEUE</span><strong>Queued</strong></div><div class="task"><b>Webhook intake</b><small>fingerprint → normalize</small></div></div><div class="lane"><div class="lane-head"><span>RUN</span><strong>Running</strong></div><div class="task"><b>Signal scoring</b><small>evidence → confidence</small></div></div><div class="lane"><div class="lane-head"><span>VERIFY</span><strong>Review</strong></div><div class="task"><b>Human approval</b><small>sensitive action gate</small></div></div><div class="lane"><div class="lane-head"><span>BLOCKED</span><strong>Blocked</strong></div><div class="task"><i class="task-dot red"></i><b>Provider quota</b><small>reported, never hidden</small></div></div></div></div>'}
function trading(){var t=S.personal.trades||[];return title("Algorithmic Trading Terminal","PAPER-FIRST: تحليل بصري متقدم، بلا أوامر حية من الواجهة.",'<button class="btn primary" data-action="paperTrade">＋ Paper Trade</button><button class="btn" data-action="terminal">⌘ Terminal</button>')+'<div class="terminal-grid"><div>'+card("Market Surface","VISUAL ANALYTICS",spark()+'<div class="stat-grid" style="margin-top:9px"><div class="micro-stat"><b>SIM</b><span>mode</span></div><div class="micro-stat"><b>0</b><span>live orders</span></div><div class="micro-stat"><b>'+t.length+'</b><span>paper ideas</span></div></div>')+'</div><div class="terminal-side">'+card("Risk Envelope","GUARDRAILS",'<div class="stack"><div class="rowbox"><div class="row-main"><b>Custody</b><small>no private keys</small></div>'+pill("ISOLATED","green")+'</div><div class="rowbox"><div class="row-main"><b>Execution</b><small>live trading disabled</small></div>'+pill("OFF","green")+'</div></div>')+card("Recent Ideas","PAPER LEDGER",t.length?'<div class="stack">'+t.slice(-5).reverse().map(function(x){return '<div class="rowbox"><div class="row-main"><b>'+esc(x.asset)+'</b><small>'+esc(x.side)+' · entry '+esc(x.entry)+' · stop '+esc(x.stop)+'</small></div>'+pill("PAPER","blue")+'</div>'}).join("")+'</div>':empty("No paper ideas","Add a hypothesis to test."))+'</div></div>'}
function clients(){var c=S.personal.clients||[];return title("Client & Workspace Hub","ملفات رقمية للعملاء والمهام والصلاحيات والاستهلاك.",'<button class="btn primary" data-action="client">＋ New Client</button>')+'<div class="grid g3">'+(c.length?c.map(function(x){return card(x.name,"WORKSPACE",'<div class="rowbox"><div class="row-main"><b>'+esc(x.name)+'</b><small>'+esc(x.scope||"automation workspace")+' · '+esc(x.status||"active")+'</small></div>'+pill(x.trust||"unverified",x.trust==="verified"?"green":"amber")+'</div><div class="sub" style="margin-top:8px">Tasks '+num(x.tasks||0)+' · Usage '+num(x.usage||0)+' · '+esc(x.updated||"—")+'</div>')}).join(""):empty("لا يوجد عميل","أضف workspace محلياً أو اربط record موثق.",'<button class="btn primary" data-action="client">＋ New Client</button>'))+'</div>'}
function terminal(){return title("Realtime Live Terminal & Logs","طرفية سوداء زجاجية للأوامر الآمنة، السجلات، وأحداث البوت.",'<button class="btn" data-action="status">Status</button><button class="btn primary" data-action="clearLogs">Clear</button>')+'<div class="terminal-grid"><div class="console"><div class="console-head"><span>MIDAD // LIVE TERMINAL</span><span id="terminalStatus">ready</span></div><div class="console-body" id="consoleBody">'+logs()+'</div><div class="console-input"><input id="terminalInput" placeholder="help | status | scan | opportunity | osint | mining | autonomy | route dashboard"><button data-action="terminalRun">RUN</button></div></div><div class="terminal-side">'+card("Command Set","SAFE ACTIONS",'<div class="stack">'+["help","status","scan","opportunity","osint","mining","autonomy"].map(function(x){return '<button class="rowbox" data-command="'+x+'"><div class="row-main"><b class="mono">'+x+'</b><small>safe runtime command</small></div>↵</button>'}).join("")+'</div>')+card("Known Blockers","RUNTIME SNAPSHOT",'<div class="stack">'+C.knownRuntimeSnapshot.incidents.map(function(x){return '<div class="alert '+x.severity+'"><b>'+esc(x.title)+'</b><p>'+esc(x.detail)+'</p></div>'}).join("")+'</div>')+'</div></div>'}
function opportunities(){var x=S.live&&S.live.opportunities?(S.live.opportunities.items||S.live.opportunities):[];if(!Array.isArray(x))x=[];return title("Opportunity Intelligence","مصادر، evidence، confidence، payment rail، next action.",'<button class="btn primary" data-action="opportunityScan">⌁ Scan</button><button class="btn" data-action="scan">OSINT</button>')+'<div class="grid g4">'+["NEW","QUALIFIED","NEGOTIATING","WON"].map(function(s){return card(s,"PIPELINE",'<div class="metric">'+x.filter(function(i){return String(i.stage||"NEW").toUpperCase()===s}).length+'</div><div class="sub">current payload</div>')}).join("")+'</div><div class="card" style="margin-top:12px">'+(x.length?'<div class="table-wrap"><table class="table"><thead><tr><th>Opportunity</th><th>Stage</th><th>Source</th><th>Payment</th><th>Confidence</th></tr></thead><tbody>'+x.map(function(i){return '<tr><td><b>'+esc(i.title||i.name||"—")+'</b></td><td>'+pill(i.stage||"review","blue")+'</td><td>'+esc(i.source||"—")+'</td><td>'+esc(i.payment_method||"—")+'</td><td>'+esc(i.confidence==null?"—":Math.round(Number(i.confidence)*(Number(i.confidence)>1?1:100))+"%")+'</td></tr>'}).join("")+'</tbody></table></div>':empty("No verified opportunities","Run a scan when the relevant runtime is available."))+'</div>'}
function revenue(){return title("Revenue Engine","Prospect → offer → milestone → invoice → collect.",'<button class="btn primary" data-action="client">＋ Prospect</button><button class="btn" data-action="recordIncome">＋ Income</button>')+'<div class="grid g4">'+["Prospects","Proposals","Negotiating","Receivables"].map(function(x){return card(x,"PIPELINE",'<div class="metric">—</div><div class="sub">No verified live total</div>')}).join("")+'</div><div class="grid g3" style="margin-top:12px">'+["$99 Quick Fix","$199 Automation Sprint","$399+ System Slice"].map(function(x,i){return card(x.split(" ").slice(1).join(" "),"OFFER 0"+(i+1),'<div class="metric">'+x.split(" ")[0]+'</div><div class="sub">milestone-first service</div>')}).join("")+'</div>'}
function capital(){return title("Capital Command","مصادر المال، التكلفة، السيولة، والـrunway مع حدود مخاطر واضحة.",'<button class="btn primary" data-action="recordIncome">＋ Income</button>')+'<div class="grid g4">'+["Available","Committed","Costs","Runway"].map(function(x){return card(x,"CAPITAL",'<div class="metric">—</div><div class="sub">awaiting verified source</div>')}).join("")+'</div><div class="grid g2" style="margin-top:12px">'+card("Capital Sources","SOURCES",empty("No verified sources","Mining appears here after trusted backend data."))+card("Risk Envelope","PROTECTION",'<div class="stack"><div class="rowbox"><div class="row-main"><b>Live trade</b><small>disabled by default</small></div>'+pill("OFF","green")+'</div><div class="rowbox"><div class="row-main"><b>Transfers</b><small>human approval</small></div>'+pill("GATED","blue")+'</div></div>')+'</div>'}
function wallets(){var w=S.personal.wallets||[];return title("Wallet Control","فصل المحافظ الشخصية عن التشغيلية. العنوان العام فقط.",'<button class="btn primary" data-action="wallet">＋ Add Wallet</button>')+'<div class="grid g2">'+card("Operational","SYSTEM",empty("No operational wallet exposed","Backend-controlled wallets remain hidden until verified."))+card("Personal","PRIVATE",w.length?'<div class="stack">'+w.map(function(x,i){return '<div class="rowbox"><div class="row-main"><b>'+esc(x.label)+'</b><small class="mono">'+esc(x.address)+' · '+esc(x.network)+'</small></div><button class="btn danger" data-remove-wallet="'+i+'">Delete</button></div>'}).join("")+'</div>':empty("No personal wallet","Add a public address only.",'<button class="btn primary" data-action="wallet">＋ Add</button>'))+'</div>'}
function mining(){var a=S.live&&S.live.mining&&S.live.mining.accounts||[];return title("Mining Command","ViaBTC ومعدّات التعدين كمسار رأس مال مستقل.",'<button class="btn primary" data-action="mining">⛏ Run Monitor</button>')+'<div class="grid g4">'+[["M31+","84 TH/s"],["M21","56 TH/s"],["POOL","ViaBTC"],["MODE","READ ONLY"]].map(function(x){return card(x[0],"MINING",'<div class="metric metric-sm">'+x[1]+'</div><div class="sub">known configuration snapshot</div>')}).join("")+'</div><div class="card" style="margin-top:12px">'+(a.length?'<div class="table-wrap"><table class="table"><thead><tr><th>Account</th><th>Status</th><th>Hashrate</th><th>Workers</th></tr></thead><tbody>'+a.map(function(i){return '<tr><td>'+esc(i.label)+'</td><td>'+pill(i.status||"unknown",i.status==="connected"?"green":"amber")+'</td><td>'+num(i.last_hashrate_ths)+' TH/s</td><td>'+num(i.last_worker_count)+'</td></tr>'}).join("")+'</tbody></table></div>':empty("Live mining data not verified","Run the monitor action when the ViaBTC runtime is available."))+'</div>'}
function intel(){var s=S.live&&S.live.signals||[];if(!Array.isArray(s))s=[];return title("Intelligence & OSINT","Signal → evidence → fingerprint → confidence → opportunity.",'<button class="btn primary" data-action="scan">⌁ Run OSINT Scan</button>')+'<div class="grid g4">'+["Signals","High Confidence","Entities","Anomalies"].map(function(x,i){return card(x,"INTELLIGENCE",'<div class="metric">'+(i===0?num(s.length):"—")+'</div><div class="sub">current verified payload</div>')}).join("")+'</div><div class="card" style="margin-top:12px">'+(s.length?'<div class="table-wrap"><table class="table"><thead><tr><th>Signal</th><th>Source</th><th>Score</th><th>Confidence</th></tr></thead><tbody>'+s.map(function(x){return '<tr><td><b>'+esc(x.type_label||x.type||"signal")+'</b><div class="sub">'+esc(x.entity||"")+'</div></td><td>'+esc(x.source||"—")+'</td><td>'+num(x.score)+'</td><td>'+esc(x.confidence==null?"—":Math.round(Number(x.confidence)*(Number(x.confidence)>1?1:100))+"%")+'</td></tr>'}).join("")+'</tbody></table></div>':empty("No verified OSINT feed","Run a scan and let the backend populate the evidence stream."))+'</div>'}
function alerts(){var a=S.live&&S.live.alerts&&S.live.alerts.items||C.knownRuntimeSnapshot.incidents;return title("Alert Engine","Severity، source، freshness، delivery state.",'<button class="btn primary" data-action="refresh">↻ Refresh</button>')+'<div class="stack">'+a.map(function(x){return '<div class="alert '+esc(x.severity||"warning")+'"><div style="display:flex;justify-content:space-between"><b>'+esc(x.title||"Alert")+'</b>'+pill(String(x.status||"observed").toUpperCase(),x.severity==="critical"?"red":"amber")+'</div><p>'+esc(x.detail||x.body||"")+'</p><div class="sub">'+esc(x.source||"unknown")+'</div></div>'}).join("")+'</div>'}
function personal(){var total=(S.personal.income||[]).reduce(function(a,x){return a+Number(x.amount||0)},0);return title("Private Workspace","دخل محلي، ملاحظات، وهوية شخصية — منفصلة عن النظام.",'<button class="btn primary" data-action="recordIncome">＋ Income</button>')+'<div class="grid g3">'+card("My Income","PRIVATE",'<div class="metric">'+money(total)+'</div><div class="sub">local-only record</div>')+card("My Notes","PRIVATE",'<textarea id="noteField" class="field" style="width:100%;min-height:120px">'+esc(S.personal.notes||"")+'</textarea><div style="margin-top:8px"><button class="btn primary" data-action="saveNote">Save Note</button></div>')+card("Identity","PROFILE",'<div class="rowbox"><div class="row-main"><b>'+esc(S.user.name||"MIDAD User")+'</b><small>'+esc(S.user.email||"No verified email")+'</small></div>'+pill(S.connected?"VERIFIED":"UNVERIFIED",S.connected?"green":"amber")+'</div>')+'</div>'}
function settings(){return title("Control Settings","الاتصال، المظهر، وguardrails.",'<button class="btn primary" data-action="saveSettings">Save</button>')+'<div class="grid g2">'+card("Connection","CONTROL ROOM",'<div class="form-grid"><div class="field"><label>Browser access key</label><input id="accessKey" type="password" placeholder="optional / not persisted"></div><div class="field"><label>Telegram</label><input disabled value="'+(TG()&&TG().initData?"Detected":"Not detected")+'"></div></div><div style="margin-top:10px"><button class="btn primary" data-action="connect">Connect / Verify</button><button class="btn" data-action="disconnect">Disconnect</button></div>')+card("Safety","GUARDRAILS",'<div class="stack"><div class="rowbox"><div class="row-main"><b>Private keys</b><small>never stored</small></div>'+pill("FORBIDDEN","green")+'</div><div class="rowbox"><div class="row-main"><b>Live trading</b><small>paper only</small></div>'+pill("OFF","green")+'</div><div class="rowbox"><div class="row-main"><b>Financial / destructive</b><small>human approval</small></div>'+pill("GATED","blue")+'</div></div>')+card("Workspace","MODULAR",'<div class="sub">Dashboard modules are draggable and persisted locally.</div><div style="margin-top:9px"><button class="btn" data-action="reset">Reset workspace</button></div>')+'</div>'}
function health(){return title("System Health","Verified، Degraded، أو Unverified — بلا ادعاء نجاح.",'<button class="btn primary" data-action="refresh">↻ Probe</button>')+'<div class="grid g3">'+["Supabase","n8n","Telegram","Vespa","TinyFish","GitHub Pages"].map(function(x){return card(x,"SYSTEM",'<div class="metric metric-sm">'+(x==="Supabase"&&S.connected?"VERIFIED":"UNVERIFIED")+'</div><div class="sub">'+x+' operational channel</div>'+pill(x==="Supabase"&&S.connected?"LIVE":"NO LIVE PROBE",x==="Supabase"&&S.connected?"green":"amber"));}).join("")+"</div>"}
function revenueEmpty(t,d){return '<div style="padding:24px;text-align:center;border:1px dashed rgba(154,175,205,.14);border-radius:15px"><b>'+esc(t)+'</b><div class="sub" style="margin-top:5px">'+esc(d)+'</div></div>'}
function empty(t,d,a){return revenueEmpty(t,d)+(a||"")}
function needs(){var n=S.live&&S.live.approvals||[];if(!n.length)return empty("Nothing needs you","No verified approval records in current payload.");return n.map(function(x){return '<div class="alert warning"><b>'+esc(x.action||x.title||"Approval")+'</b><p>'+esc(x.reason||"Human approval required.")+'</p><button class="btn primary" data-approval="'+esc(x.id)+'" data-decision="approved">Approve</button> <button class="btn danger" data-approval="'+esc(x.id)+'" data-decision="rejected">Reject</button></div>'}).join("")}
function ensureSession(){
  if(S.sessionToken)return Promise.resolve(S.sessionToken);
  var url=C.supabaseUrl+C.controlRoomFunction;
  var requestId="auth-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,8);
  var tg=TG()&&TG().initData||"";
  var body={request_id:requestId,client:"midad-control-room",client_version:C.buildVersion||"unknown",telegram_init_data:tg,access_key:S.accessKey||""};
  return fetch(url,{method:"POST",headers:{"Content-Type":"application/json","X-MIDAD-Request-ID":requestId,"X-MIDAD-Client":"control-room"},body:JSON.stringify(body)})
    .then(function(r){return r.json().catch(function(){return{}}).then(function(j){
      if(!r.ok||!j||!j.ok||!j.token)throw new Error((j&&j.error)||("AUTH HTTP "+r.status));
      S.sessionToken=j.token;
      S.connected=true;
      S.label="CONNECTED / VERIFIED";
      return j.token;
    })});
}
function api(action,extra,retry){
  var url=C.supabaseUrl+C.controlRoomFunction;
  return ensureSession().then(function(){
    var requestId="ui-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,8);
    var body=Object.assign({action:action,operation:action,request_id:requestId,client:"midad-control-room",client_version:C.buildVersion||"unknown",token:S.sessionToken},extra||{});
    return fetch(url,{method:"POST",headers:{"Content-Type":"application/json","X-MIDAD-Request-ID":requestId,"X-MIDAD-Client":"control-room"},body:JSON.stringify(body)})
      .then(function(r){return r.json().catch(function(){return{}}).then(function(j){
        if(!r.ok||j&&((j.ok===false)||(j.success===false)||(j.status==="error")||j.error)){
          var msg=(j&&j.error&&typeof j.error==="object"?(j.error.message||j.error.detail||JSON.stringify(j.error)):j&&j.error)||j&&j.message||("HTTP "+r.status);
          if(r.status===401&&!retry&&msg==="session_expired"){
            S.sessionToken="";
            S.connected=false;
            return api(action,extra,true);
          }
          throw new Error(msg);
        }
        return j;
      })});
  });
}
function connect(silent){
  S.accessKey=(($("#accessKey")&&$("#accessKey").value)||S.accessKey||"").trim();
  log("Connecting…");
  return api(C.dashboardAction).then(function(j){
    S.connected=true;
    S.label="CONNECTED / VERIFIED";
    S.live=j.dashboard||j.data||j;
    S.user=j.user||S.live.user||{};
    log("Verified backend context","ok");
    toast("تم التحقق من الاتصال.","good");
    render();
  }).catch(function(e){
    S.connected=false;
    if(e.message==="session_expired")S.sessionToken="";
    S.label="DEGRADED / AWAITING VERIFY";
    log("Connection failed: "+e.message,"warn");
    if(!silent)toast("تعذر التحقق: "+e.message,"warn");
    render();
  });
}
function act(a,label){log("→ "+label);return api(a).then(function(j){if(j.dashboard)S.live=j.dashboard;else S.live=Object.assign({},S.live||{},j);log("✓ "+label+" completed","ok");toast(label+" تم تنفيذها.","good");render()}).catch(function(e){log("✕ "+label+": "+e.message,"err");toast(label+" فشلت: "+e.message,"bad")})}
function modal(titleTxt,fields,saveFn){var m=$("#modal"),b=$("#modalBox");b.innerHTML='<h3>'+esc(titleTxt)+'</h3><p>سجل محلي. لا تدخل seed phrase أو private key.</p><div class="form-grid">'+fields.map(function(f){return '<div class="field"><label>'+esc(f[1])+'</label><input id="mf_'+f[0]+'" type="'+(f[2]||"text")+'"></div>'}).join("")+'</div><div style="margin-top:13px;text-align:left"><button class="btn" id="cancelModal">Cancel</button> <button class="btn primary" id="saveModal">Save</button></div>';m.classList.add("open");$("#cancelModal").onclick=function(){m.classList.remove("open")};$("#saveModal").onclick=function(){var v=function(k){return ($("#mf_"+k)&&$("#mf_"+k).value||"").trim()};saveFn(v);m.classList.remove("open");save();render();toast("تم الحفظ محلياً.","good")}}
function commandOpen(){var c=$("#command");c.classList.add("open");var i=$("#cmdInput");var rows=R.map(function(r){return{kind:"route",id:r[0],t:r[1],m:r[2]}}).concat(["scan","opportunityScan","mining","autonomy","status","terminal"].map(function(a){return{kind:"action",id:a,t:a,m:"safe action"}}));$("#cmdList").innerHTML=rows.map(function(x,i){return '<div class="cmd-row '+(i===0?"active":"")+'" data-id="'+x.id+'" data-kind="'+x.kind+'"><div class="nav-ico">'+(I[x.id]||"⌁")+'</div><div><b>'+esc(x.t)+'</b><small>'+esc(x.m)+'</small></div></div>'}).join("");$("#cmdInput").value="";$("#cmdInput").focus();$("#cmdInput").oninput=function(){var q=this.value.toLowerCase();$("#cmdList").querySelectorAll(".cmd-row").forEach(function(x){x.style.display=x.textContent.toLowerCase().indexOf(q)>=0?"flex":"none"})};$("#cmdList").querySelectorAll(".cmd-row").forEach(function(x){x.onclick=function(){c.classList.remove("open");if(x.dataset.kind==="route")go(x.dataset.id);else action(x.dataset.id)}})}
function terminalCommand(c){var p=c.toLowerCase().trim();if(p==="help")return log("help | status | scan | opportunity | osint | mining | autonomy | route <page>","ok");if(p==="status")return log(S.connected?"CONNECTED / VERIFIED":"DEGRADED / AWAITING VERIFY",S.connected?"ok":"warn");if(p.indexOf("route ")===0)return go(p.split(" ")[1]||"dashboard");if(p==="scan"||p==="osint")return act("run_osint_scan","OSINT scan");if(p==="opportunity")return act("run_opportunity_scan","Opportunity scan");if(p==="mining")return act("run_mining_monitor","Mining monitor");if(p==="autonomy")return act("run_autonomy_now","Autonomy cycle");log("Unknown command. Type help.","warn")}
function action(a){if(a==="menu")return $("#sidebar").classList.toggle("open");if(a==="command")return commandOpen();if(a==="needs")return $("#drawer").classList.toggle("open");if(a==="connect")return connect(false);if(a==="disconnect"){S.connected=false;S.sessionToken="";S.label="DISCONNECTED";S.live=null;return render()}if(a==="refresh"||a==="status")return connect(true);if(a==="scan")return act("run_osint_scan","OSINT scan");if(a==="opportunityScan")return act("run_opportunity_scan","Opportunity scan");if(a==="mining")return act("run_mining_monitor","Mining monitor");if(a==="autonomy")return act("run_autonomy_now","Autonomy cycle");if(a==="terminal")return go("terminal");if(a==="clearLogs"){S.logs=[];return render()}if(a==="reset"){S.modules=["neural","metrics","market","activity","health","quick"];localStorage.setItem("midad_ui_modules",JSON.stringify(S.modules));return render()}if(a==="saveNote"){S.personal.notes=($("#noteField")&&$("#noteField").value)||"";save();return toast("تم حفظ الملاحظة.","good")}if(a==="saveSettings"){S.accessKey=(($("#accessKey")&&$("#accessKey").value)||"").trim();return toast("تم حفظ إعدادات الجلسة لهذا التبويب.","good")}if(a==="recordIncome")return modal("Record Income",[["title","Description"],["amount","Amount USD","number"]],function(v){S.personal.income.push({title:v("title"),amount:Number(v("amount")||0),t:new Date().toISOString()})});if(a==="wallet")return modal("Add Personal Wallet",[["label","Label"],["address","Public address"],["network","Network"]],function(v){S.personal.wallets.push({label:v("label"),address:v("address"),network:v("network")})});if(a==="paperTrade")return modal("Add Paper Trade",[["asset","Asset"],["side","Side"],["entry","Entry"],["stop","Stop"],["target","Target"]],function(v){S.personal.trades.push({asset:v("asset"),side:v("side"),entry:v("entry"),stop:v("stop"),target:v("target")})});if(a==="client")return modal("New Client / Workspace",[["name","Client / Project"],["scope","Scope"],["trust","Trust state"]],function(v){S.personal.clients.push({name:v("name"),scope:v("scope"),trust:v("trust")||"unverified",status:"active",updated:new Date().toLocaleString(),tasks:0,usage:0})});if(a==="terminalRun"){var i=$("#terminalInput");terminalCommand(i.value);i.value=""}}
function go(id){if(!R.some(function(r){return r[0]===id}))return;S.route=id;location.hash=id;render();window.scrollTo({top:0,behavior:"smooth"})}
function bind(){document.querySelectorAll("[data-route]").forEach(function(x){x.onclick=function(){go(x.dataset.route)}});document.querySelectorAll("[data-action]").forEach(function(x){x.onclick=function(e){e.stopPropagation();action(x.dataset.action)}});document.querySelectorAll("[data-command]").forEach(function(x){x.onclick=function(){terminalCommand(x.dataset.command)}});document.querySelectorAll("[data-remove-wallet]").forEach(function(x){x.onclick=function(){S.personal.wallets.splice(Number(x.dataset.removeWallet),1);save();render();toast("Deleted.","good")}});document.querySelectorAll("[data-approval]").forEach(function(x){x.onclick=function(){api("approval_decide",{approval_id:x.dataset.approval,decision:x.dataset.decision,note:"Decision from MIDAD Neural UI"}).then(function(){toast("Approval updated.","good");connect(true)}).catch(function(e){toast(e.message,"bad")})}});var ti=$("#terminalInput");if(ti)ti.onkeydown=function(e){if(e.key==="Enter")action("terminalRun")};window.onkeydown=function(e){if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();commandOpen()}if(e.key==="Escape"){$("#command").classList.remove("open");$("#drawer").classList.remove("open")}}}
function render(){shell();if(S.route==="dashboard")inject();bind();if(typeof window.__MIDAD_APPLY_TYPOGRAPHY==="function")window.__MIDAD_APPLY_TYPOGRAPHY()}
window.addEventListener("hashchange",function(){var h=location.hash.slice(1);if(R.some(function(r){return r[0]===h})){S.route=h;render()}});
if(TG())try{TG().ready();TG().expand();if(TG().enableClosingConfirmation)TG().enableClosingConfirmation()}catch(e){}
render();log("MAXIMUM Neural UI v5 booted","ok");
window.__MIDAD_RUNTIME_READY=true;
setInterval(function(){if(S.connected)connect(true)},30000);
})();