(()=>{
"use strict";
const API="https://froegigfmpmvtecztfb.supabase.co/functions/v1/midad_iaitrader_station";
const TG=()=>window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null;
const S={view:"overview",initData:"",data:null,result:null,busy:false,error:""};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const num=v=>v==null?"—":Number(v).toLocaleString("en-US",{maximumFractionDigits:2});
function tgH(){try{TG()?.HapticFeedback?.impactOccurred("light")}catch{}}
function toast(msg){const d=document.createElement("div");d.className="toast";d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),3200)}
async function call(action,extra={}){if(!S.initData)throw new Error("افتح المحطة من Telegram.");const r=await fetch(API,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({telegram_init_data:S.initData,action,...extra}),signal:AbortSignal.timeout(90000)});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw new Error(j.error||"station_request_failed");return j}
async function refresh(){if(S.busy)return;S.busy=true;render();try{S.data=await call("overview");S.error=""}catch(e){S.error=String(e.message||e)}finally{S.busy=false;render()}}
async function analyze(){if(S.busy)return;S.busy=true;render();try{S.result=await call("analyze");await call("overview").then(x=>S.data=x);toast("تم تحديث تحليل iAiTrader")}catch(e){S.error=String(e.message||e);toast("فشل التحليل: "+S.error)}finally{S.busy=false;render()}}
async function lock(){try{const j=await call("lock");toast(j.ok?"تم قفل Governor التداول.":"تعذر القفل");await refresh()}catch(e){toast("تعذر القفل: "+e.message)}}
async function prepare(){const market=$("#pm")?.value?.trim().toUpperCase()||"BTCUSDT";const provider=$("#pp")?.value||"coinex";const side=$("#ps")?.value||"buy";const amount=Number($("#pa")?.value||1);try{const j=await call("prepare",{market,provider,side,amount});$("#prepareMsg").innerHTML='<div class="notice"><b>النتيجة:</b> '+esc(JSON.stringify(j.result||j))+'</div>'}catch(e){$("#prepareMsg").innerHTML='<div class="notice"><b>Blocked:</b> '+esc(e.message||e)+'</div>'}}
function openPrepare(){const old=$("#prepareModal");if(old)old.remove();document.body.insertAdjacentHTML("beforeend",'<div id="prepareModal" class="modal"><section class="panel"><div class="head"><div><div class="eyebrow">PREPARE / NO LIVE ORDER</div><h3>إنشاء مرشح تداول</h3><small>هذه الخطوة تحضيرية فقط ولا ترسل أمرًا حيًا.</small></div><button class="btn" data-cmd="closeModal">إغلاق</button></div><div class="form"><label>السوق<input id="pm" value="BTCUSDT"></label><label>المزوّد<select id="pp"><option value="coinex">CoinEx</option><option value="weex">WEEX</option></select></label><label>الجانب<select id="ps"><option value="buy">شراء</option><option value="sell">بيع</option><option value="watch">مراقبة</option></select></label><label>القيمة بالدولار<input id="pa" type="number" min="0.01" step="0.01" value="1"></label><div class="hero-actions"><button class="btn primary" data-cmd="prepare">حضّر المرشح</button></div><div id="prepareMsg"></div></div></section></div>');$("#prepareModal").addEventListener("click",e=>{if(e.target.id==="prepareModal")e.currentTarget.remove()})}
function stateBadge(v){const s=String(v||"—").toUpperCase();const c=["ACTIVE","VERIFIED","READY","PAPER","LIVE"].includes(s)?"green":["FAILED","BLOCKED"].includes(s)?"red":"amber";return '<span class="badge '+c+'">'+esc(s)+'</span>'}
function shell(){const a=$("#app");a.innerHTML='<div id="tr"><header class="top"><div class="brand"><div class="mark"><b>₿</b></div><div><strong>iAiTrader</strong><small>TRADING STATION</small></div></div><div class="top-actions"><div class="status '+(S.data?"live":"")+'"><i></i><span>'+(S.data?"متصل":"مقفلة")+'</span></div><button class="icon" data-cmd="refresh">↻</button></div></header><main class="wrap" id="views"></main><nav class="nav"><button data-view="overview">◉<span>المقود</span></button><button data-view="signal">◈<span>الإشارة</span></button><button data-view="risk">🛡<span>المخاطر</span></button><button data-view="paper">▣<span>Paper</span></button><button data-view="more">☷<span>المزيد</span></button></nav></div>'}
function overview(){const g=S.data?.governor||{},p=S.data?.paper_trades||[],c=S.data?.connectors||[],s=S.data?.signals||[],last=S.result?.signal||null;return '<div class="page"><section class="panel hero"><div><div class="eyebrow">MIDAD / IAITRADER · INDEPENDENT TRADING</div><h1>لا ننسخ السوق.<br><span>نحلّل ونختبر ونقيس.</span></h1><p>محطة تداول مستقلة مرتبطة بـMIDAD Core. تستخدم محرك non-copy الموجود، وتجمع السوق والمخاطر وPaper Learning. التنفيذ الحي مقفول.</p><div class="hero-actions"><button class="btn primary" data-cmd="analyze">'+(S.busy?"جارٍ التحليل…":"🧠 حلّل الآن")+'</button><button class="btn green" data-view="paper">▣ Paper Trade</button><button class="btn warn" data-cmd="lock">🔒 Lock</button></div></div><div class="orbit"><div class="orbit-core"><div><b>iAiTrader</b><small>'+esc(g.mode||"PAPER")+'</small></div></div></div></section><section class="kpis"><div class="kpi"><span>MODE</span><b>'+esc(g.mode||"paper")+'</b><small>Governor</small></div><div class="kpi"><span>OPEN PAPER</span><b>'+p.filter(x=>["open","review"].includes(String(x.status))).length+'</b><small>تجارب مفتوحة</small></div><div class="kpi"><span>SIGNALS</span><b>'+s.length+'</b><small>آخر الإشارات</small></div><div class="kpi"><span>CONNECTORS</span><b>'+c.length+'</b><small>مزودون مسجلون</small></div><div class="kpi"><span>LIVE</span><b>LOCKED</b><small>لا أوامر حية</small></div></section><section class="grid2 section"><div class="panel section"><div class="head"><div><div class="eyebrow">LATEST SIGNAL</div><h2>آخر قراءة</h2></div>'+stateBadge(last?.direction||s[0]?.payload?.direction||"WAIT")+'</div><div class="signal"><div class="signal-title"><h2>'+esc(last?.direction||s[0]?.payload?.direction||"WAIT")+'</h2><span class="badge cyan">'+(last?.confidence!=null?(Number(last.confidence)*100).toFixed(1)+"%":"—")+'</span></div><div class="signal-meta"><span class="badge">FACT: multi-venue</span><span class="badge">non-copy</span><span class="badge">paper-only</span></div><div class="reason">'+esc(last?.features?.regime?"Regime: "+last.features.regime:"اضغط تحليل الآن لإنتاج قراءة جديدة.")+'</div></div></div><div class="panel section"><div class="head"><div><div class="eyebrow">CONNECTORS</div><h2>جاهزية المزودين</h2></div></div><div class="cards">'+(c.slice(0,6).map(x=>'<div class="card"><b>'+esc(x.label||x.provider||"Provider")+'</b><p>'+esc(x.provider||"—")+' · '+stateBadge(x.status||"unknown")+'</p></div>').join("")||'<div class="empty">لا توجد connectors مسجلة.</div>')+'</div></div></section></div>'}
function signal(){const j=S.result||{},s=j.signal||{},r=j.risk||{},f=j.features||{},e=j.evidence||{};return '<div class="page"><section class="panel section"><div class="head"><div><div class="eyebrow">SIGNAL MATRIX</div><h2>الإشارة المستقلة</h2><small>Evidence → Signal → Risk Gate</small></div>'+stateBadge(s.direction)+'</div><div class="facts"><div class="fact"><span>DIRECTION</span><b>'+esc(s.direction||"NEUTRAL")+'</b></div><div class="fact"><span>CONFIDENCE</span><b>'+esc(s.confidence==null?"—":(Number(s.confidence)*100).toFixed(1)+"%")+'</b></div><div class="fact"><span>ENTRY</span><b>'+esc(s.entry??"—")+'</b></div><div class="fact"><span>STOP</span><b>'+esc(s.stop??"—")+'</b></div><div class="fact"><span>TARGET</span><b>'+esc(s.take_profit??"—")+'</b></div><div class="fact"><span>REGIME</span><b>'+esc(f.regime||"—")+'</b></div><div class="fact"><span>AGREEMENT</span><b>'+esc(f.agreement??"—")+'</b></div><div class="fact"><span>SPREAD</span><b>'+esc(f.max_spread_pct==null?"—":f.max_spread_pct+"%")+'</b></div></div><div class="reason"><b>Risk:</b> '+esc(r.class||"—")+' · <b>Gate:</b> '+esc(r.gate_decision||"—")+' · <b>Paper:</b> '+(j.paper_trade?esc(j.paper_trade.status):"NOT_CREATED")+'</div></section><section class="grid2 section"><div class="panel section"><div class="head"><div><div class="eyebrow">MARKET EVIDENCE</div><h3>المصادر المستقلة</h3></div></div><div class="cards">'+((e.market_sources||[]).map(x=>'<div class="card"><b>'+esc(x.source||"source")+'</b><p>'+esc(x.symbol||"BTC")+' · price '+esc(x.price??"—")+' · 24h '+esc(x.change_24h_pct??"—")+'%</p></div>').join("")||'<div class="empty">شغّل التحليل لإحضار الأدلة.</div>')+'</div></div><div class="panel section"><div class="head"><div><div class="eyebrow">LANES</div><h3>المسارات</h3></div></div><div class="cards">'+((f.strategy_lanes||[]).map(x=>'<div class="card"><b>'+esc(String(x.id||"lane").replace(/_/g," "))+'</b><p>'+stateBadge(x.state)+' · '+esc(x.direction||"NEUTRAL")+' · '+num(x.score)+'</p></div>').join("")||'<div class="empty">لا توجد lanes بعد.</div>')+'</div></div></section></div>'}
function risk(){const g=S.data?.governor||{};return '<div class="page"><section class="panel section"><div class="head"><div><div class="eyebrow">RISK GOVERNOR</div><h2>بوابة المخاطر</h2><small>التداول الحي مغلق. هذه الحدود تحكم محطة iAiTrader عندما تصبح هناك صلاحية تشغيل لاحقة.</small></div><span class="badge '+(g.kill_switch?"red":"green")+'">'+(g.kill_switch?"LOCKED":"UNLOCKED")+'</span></div><div class="facts"><div class="fact"><span>ORDER CAP</span><b>$'+esc(g.max_order_usd??"—")+'</b></div><div class="fact"><span>POSITION CAP</span><b>$'+esc(g.max_position_usd??"—")+'</b></div><div class="fact"><span>DAILY LOSS</span><b>$'+esc(g.max_daily_loss_usd??"—")+'</b></div><div class="fact"><span>DAILY TRADES</span><b>'+esc(g.max_daily_trades??"—")+'</b></div><div class="fact"><span>CONFIDENCE</span><b>'+esc(g.min_signal_confidence==null?"—":(Number(g.min_signal_confidence)*100).toFixed(1)+"%")+'</b></div><div class="fact"><span>MIN EDGE</span><b>'+esc(g.min_expected_net_edge_pct??"—")+'%</b></div><div class="fact"><span>MULTI-SOURCE</span><b>'+esc(g.require_multi_source_confirmation?"ON":"OFF")+'</b></div><div class="fact"><span>LEVERAGE</span><b>'+esc(g.leverage_allowed?"ON":"OFF")+'</b></div></div><div class="hero-actions"><button class="btn warn" data-cmd="lock">🔒 فرض القفل الآن</button></div></section><section class="panel section"><div class="notice"><b>ملاحظة:</b> إلغاء الـkill switch أو تفعيل live execution لا يتم من هذه الواجهة حاليًا؛ يبقى خلف مسار Policy + Human Approval + Provider Verification.</div></section></div>'}
function paper(){const p=S.data?.paper_trades||[];return '<div class="page"><section class="panel section"><div class="head"><div><div class="eyebrow">PAPER LAB</div><h2>مختبر التداول الورقي</h2><small>نتائج قابلة للقياس قبل أي انتقال إلى صلاحية مالية.</small></div><button class="btn primary" data-cmd="prepare">تحضير مرشح</button></div><div class="cards">'+(p.slice(0,12).map(x=>'<article class="card"><div style="display:flex;justify-content:space-between;gap:7px"><b>'+esc(x.asset_symbol||"BTC")+' · '+esc(x.direction||"NEUTRAL")+'</b>'+stateBadge(x.status)+'</div><p>Entry '+esc(x.entry_price??"—")+' · Stop '+esc(x.stop_price??"—")+' · TP '+esc(x.take_profit_price??"—")+'</p><p>Confidence '+(x.confidence==null?"—":(Number(x.confidence)*100).toFixed(1)+"%")+' · Gate '+esc(x.gate_decision||"—")+'</p><p>Outcome '+esc(x.outcome_return_pct==null?"pending":Number(x.outcome_return_pct).toFixed(2)+"%")+' · '+esc(x.outcome_label||"")+'</p></article>').join("")||'<div class="empty">لا توجد Paper Trades بعد.</div>')+'</div></section></div>'}
function more(){return '<div class="page"><section class="panel section"><div class="head"><div><div class="eyebrow">STATION IDENTITY</div><h2>iAiTrader داخل MIDAD</h2></div><span class="badge green">INDEPENDENT</span></div><div class="cards"><div class="card"><b>👁 Market</b><p>Multi-venue evidence من مصادر مستقلة.</p></div><div class="card"><b>🧠 Intelligence</b><p>يستخدم MIDAD Non-Copy Trading Engine المشترك.</p></div><div class="card"><b>🛡 Risk</b><p>Governor منفصل بحدود صغيرة وKill Switch.</p></div><div class="card"><b>⛏ ViaBTC</b><p>ترابط خلفي فقط: mining economics قد تُستخدم كـmodifier، لكن ViaBTC لا يملك التداول.</p></div><div class="card"><b>💰 Treasury</b><p>يمكن للـFinance Station تجهيز intents؛ التنفيذ المالي الحي مقفول.</p></div><div class="card"><b>🔐 Security</b><p>المصادقة من Telegram WebApp ولا أسرار في GitHub أو الواجهة.</p></div></div><div class="hero-actions"><a class="btn" href="https://t.me/iAiTrader_bot" target="_blank" rel="noopener">فتح @iAiTrader_bot</a><a class="btn" href="./index.html?v=20261003" target="_blank" rel="noopener">العودة إلى Control Room</a></div></section></div>'}
function lock(){return '<div class="page"><section class="panel section" style="max-width:680px;margin:10vh auto"><div class="eyebrow">SECURE TRADING STATION</div><h2 style="font-size:28px;margin:8px 0">افتح iAiTrader من Telegram.</h2><p style="color:#98a6b8;line-height:1.8">هذه المحطة تتحقق من Telegram WebApp initData بواسطة هوية @iAiTrader_bot. لا تستخدم Access Key هنا ولا تدخل أي secret.</p><div class="notice"><b>الحالة:</b> لا توجد Telegram session موثقة.</div><div class="hero-actions"><a class="btn primary" href="https://t.me/iAiTrader_bot" target="_blank" rel="noopener">فتح @iAiTrader_bot</a></div></section></div>'}
function render(){shell();const v=$("#views");if(!S.initData){v.innerHTML=lock();return}if(S.error&&!S.data&&!S.result){v.innerHTML='<div class="page"><section class="panel section"><div class="notice"><b>BLOCKED:</b> '+esc(S.error)+'</div><div class="hero-actions"><button class="btn primary" data-cmd="refresh">إعادة المحاولة</button></div></section></div>'}else if(S.view==="signal")v.innerHTML=signal();else if(S.view==="risk")v.innerHTML=risk();else if(S.view==="paper")v.innerHTML=paper();else if(S.view==="more")v.innerHTML=more();else v.innerHTML=overview();bind()}
function bind(){$$("[data-view]").forEach(b=>b.onclick=()=>{S.view=b.dataset.view;tgH();render()});$$("[data-cmd]").forEach(b=>b.onclick=()=>{const x=b.dataset.cmd;if(x==="refresh")refresh();else if(x==="analyze")analyze();else if(x==="lock")lock();else if(x==="prepare")openPrepare();else if(x==="closeModal")$("#prepareModal")?.remove()});}
async function boot(){const t=TG();try{t?.ready();t?.expand();t?.BackButton?.hide()}catch{}S.initData=t?.initData||"";render();if(S.initData)await refresh()}
boot();
})();