#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const requestPath = process.argv[2];
if (!requestPath) throw new Error("Usage: node mobile/factory/compile-request.mjs <request.json>");

const abs = path.isAbsolute(requestPath) ? requestPath : path.join(root, requestPath);
if (!fs.existsSync(abs)) throw new Error(`Request not found: ${abs}`);

const req = JSON.parse(fs.readFileSync(abs, "utf8"));
const required = ["product_key","display_name","app_id","version","objective"];
for (const k of required) if (!req[k]) throw new Error(`Missing request field: ${k}`);

if (!/^[a-z0-9][a-z0-9-]{1,48}$/.test(req.product_key)) throw new Error("Invalid product_key");
if (!/^\d+\.\d+\.\d+$/.test(req.version)) throw new Error("Invalid version");
if (!/^[a-zA-Z][a-zA-Z0-9]*(\.[a-zA-Z0-9]+)+$/.test(req.app_id)) throw new Error("Invalid app_id");
if (typeof req.objective !== "string" || req.objective.length > 5000) throw new Error("Invalid objective");

const factoryConfigPath = path.join(root, "mobile","factory","factory.config.json");
const factoryConfig = JSON.parse(fs.readFileSync(factoryConfigPath, "utf8"));

const existing = path.join(root,"mobile","factory","products",`${req.product_key}.json`);
if (fs.existsSync(existing)) throw new Error(`Product already exists: ${existing}`);

const baseFeatures = {
  rtl_first:true,
  local_first:true,
  native_haptics:true,
  native_back_navigation:true,
  in_app_browser:true,
  server_side_secrets_only:true,
  live_financial_execution:false,
  mission_capsules:true,
  hybrid_neural_planner:true
};

const requestedFeatures = req.features && typeof req.features === "object" ? req.features : {};
for (const [k,v] of Object.entries(requestedFeatures)) {
  if (typeof v !== "boolean") throw new Error(`Feature must be boolean: ${k}`);
  baseFeatures[k] = v;
}
if (baseFeatures.server_side_secrets_only !== true) throw new Error("Security gate: server_side_secrets_only must remain true");
if (baseFeatures.live_financial_execution === true) throw new Error("Factory gate: live financial execution is not generated by default");

const displaySafe = req.display_name.replace(/[^A-Za-z0-9_-]+/g,"-").replace(/^-+|-+$/g,"") || req.product_key;
const languages = Array.isArray(req.languages) && req.languages.length ? req.languages : factoryConfig.ui_generation.localization.supported_seed;
const markets = Array.isArray(req.target_markets) && req.target_markets.length ? req.target_markets : ["global_remote"];
const monetization = Array.isArray(req.monetization_models) && req.monetization_models.length ? req.monetization_models : ["subscription","custom_build"];
const surfaces = Array.isArray(req.surfaces) ? req.surfaces : [];

const manifest = {
  $schema:"../product.schema.json",
  schema_version:1,
  product_key:req.product_key,
  display_name:req.display_name,
  version:req.version,
  app_id:req.app_id,
  artifact_name:`${displaySafe}-v${req.version}`,
  web_entry:req.web_entry || "mobile/web/index.html",
  web_assets:Array.isArray(req.web_assets)?req.web_assets:[],
  product_mode:req.product_mode || "midad-powered",
  release_channel:req.release_channel || "debug",
  features:baseFeatures,
  surfaces,
  target_markets:markets,
  monetization_models:monetization,
  revenue_mode:req.revenue_mode || "productized",
  factory:{
    profile:"request-driven-product",
    request_driven_ui:true,
    dynamic_content:true,
    localization:{
      default_language:req.default_language || factoryConfig.ui_generation.localization.default_language,
      supported_seed:languages,
      expand_on_demand:true
    },
    learning:{
      enabled:true,
      scope:["global","product","tenant"],
      decision_policy:"evidence_weighted",
      feedback_required:true,
      objective:req.objective
    },
    quality:{
      minimum_confidence:factoryConfig.quality.minimum_confidence,
      max_repair_attempts_per_incident:factoryConfig.quality.max_repair_attempts_per_incident,
      fail_closed_on_security_gate:true,
      acceptance_tests:Array.isArray(req.acceptance_tests)?req.acceptance_tests:[]
    },
    data:{
      ...factoryConfig.data,
      requested_backend:req.backend || {}
    },
    delivery:{
      ...factoryConfig.delivery,
      request_constraints:Array.isArray(req.constraints)?req.constraints:[]
    }
  }
};

fs.mkdirSync(path.dirname(existing),{recursive:true});
fs.writeFileSync(existing,JSON.stringify(manifest,null,2)+"\n");

const requestOut=path.join(root,"mobile","factory","runtime-request.json");
fs.writeFileSync(requestOut,JSON.stringify({
  received_at:new Date().toISOString(),
  request:req,
  compiled_product:req.product_key,
  manifest_path:path.relative(root,existing)
},null,2)+"\n");

console.log(JSON.stringify({
  ok:true,
  product_key:req.product_key,
  manifest_path:path.relative(root,existing),
  runtime_request:path.relative(root,requestOut),
  version:req.version,
  languages,
  surfaces
}));
