(()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],CFG={b:localStorage.getItem("midad.bridgeUrl")||$("#bridge-url").value,a:localStorage.getItem("midad.aiUrl")||$("#ai-url").value};let S={token:localStorage.getItem("midad.omni.token")||"",tasks:[],active:null,wid:null,file:null,profile:JSON.parse(localStorage.getItem("midad.omni.profile")||"{}"),recipes:JSON.parse(localStorage.getItem("midad.omni.recipes")||"[]")};const B=()=>window.Capacitor?.Plugins?.InAppBrowser,N=()=>window.Capacitor?.Plugins?.LocalNotifications;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
async function post(u,x,h={}){const r=await fetch(u,{method:"POST",headers:{"content-type":"application/json",...h},body:JSON.stringify(x)}),t=await r.text();let d={};try{d=JSON.parse(t)}catch{d={}}if(!r.ok||d.ok===false)throw Error(d.error||"request_failed");return d}
async function br(a,x={}){if(!S.token)throw Error("الهاتف غير مقترن بـMIDAD");return post(CFG.b,{action:a,...x},{"x-midad-bridge-token":S.token})}
async function ai(a,x={}){if(!S.token)throw Error("الهاتف غير مقترن بـMIDAD");return post(CFG.a,{action:a,...x},{"x-midad-bridge-token":S.token})}
function log(m,t="info"){const e=document.createElement("div");e.className="task";e.innerHTML="<b>"+esc(m)+"</b><small>"+new Date().toLocaleTimeString("ar")+" · "+esc(t)+"</small>";$("#events").prepend(e)}
function view(id){$$(".view").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");$$(".bottom-nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===id))}
function overlay(){if($("#midad-gate"))return;const d=document.createElement("div");d.id="midad-gate";d.className="intervention-backdrop hidden";d.innerHTML='<div class="intervention-card"><div class="intervention-top"><div class="gate-icon">!</div><button id="gate-x" class="icon-btn">×</button></div><div class="eyebrow">MIDAD HUMAN INTERVENTION</div><h2 id="gate-title">تدخل مطلوب</h2><p id="gate-desc">توقفت المهمة مؤقتًا وحُفظت حالتها.</p><div id="gate-info" class="gate-box"></div><div class="intervention-actions"><button id="gate-open" class="primary">فتح الصفحة داخل MIDAD</button><button id="gate-done" class="secondary">أتممت المطلوب</button></div><small class="muted">بعد التأكيد، يرسل التطبيق إشارة الاستئناف إلى MIDAD.</small></div>';document.body.appendChild(d);$("#gate-x").onclick=()=>d.classList.add("hidden");$("#gate-open").onclick=()=>openTask();$("#gate-done").onclick=finish}
function showGate(t){overlay();S.active=t;$("#gate-title").textContent=t.title||"تدخل مطلوب";$("#gate-desc").textContent=t.instruction||t.reason||"توقف الوكيل بانتظار تدخلك.";$("#gate-info").textContent="الصفحة ستُفتح داخل MIDAD. نفّذ الخطوة المطلوبة بنفسك ثم عد واضغط «أتممت المطلوب».";$("#midad-gate").classList.remove("hidden");log("Human intervention: "+(t.title||"task"),"gate")}
async function openTask(t=S.active){if(!t?.action_url)return alert("لا يوجد رابط مرتبط بالمهمة.");if(!/^https:\/\//i.test(t.action_url))return log("تم رفض الرابط","safety");try{const b=B();if(b?.openWebView){if(S.wid&&b.bringToFront)try{return await b.bringToFront({id:S.wid})}catch{}const r=await b.openWebView({url:t.action_url,title:"MIDAD Human Intervention",toolbarType:"navigation",persistWebViewData:true,allowScreenshotsFromWebPage:false});S.wid=r.id;log("فتح الصفحة داخل التطبيق","browser")}else await window.Capacitor?.Plugins?.Browser?.open?.({url:t.action_url})}catch(e){log(e.message,"error")}}
async function finish(){if(!S.active)return;try{await br("complete_task",{task_id:S.active.id,response_data:{completed_from:"midad-omni-agent",human_confirmed:true,webview_id:S.wid||null}});log("تم الاستئناف بعد التدخل","resume");$("#midad-gate").classList.add("hidden");$("#attention")?.classList.add("hidden");if(B()?.close&&S.wid)try{await B().close({id:S.wid})}catch{}S.active=null;S.wid=null;refresh()}catch(e){log(e.message,"error")}}
async function notify(t){try{const n=N();if(!n?.schedule)return;const p=await n.checkPermissions?.();if(p?.display==="denied")return;if(p?.display!=="granted")await n.requestPermissions?.();await n.schedule({notifications:[{id:Date.now()%2147483647,title:"MIDAD — تدخل مطلوب",body:t.title||"مهمة بشرية",schedule:{at:new Date(Date.now()+500)}}]})}catch{}}
async function refresh(){try{const d=await br("list_tasks",{limit:40}),prev=new Set(S.tasks.map(x=>x.id));S.tasks=d.tasks||[];$("#task-count").textContent=S.tasks.length;$("#tasks").innerHTML=S.tasks.map(t=>'<div class="task"><b>'+esc(t.title)+'</b><small>'+esc(t.status)+' · '+esc(t.risk_class||"medium")+'</small><p>'+esc(t.instruction||t.reason||"")+'</p><div class="task-actions">'+(t.action_url?'<button class="secondary" data-open="'+esc(t.id)+'">فتح</button>':'')+'<button class="primary" data-gate="'+esc(t.id)+'">تدخل</button></div></div>').join("")||'<div class="muted">لا توجد مهام معلقة.</div>';$$("[data-open],[data-gate]").forEach(b=>b.onclick=()=>{const t=S.tasks.find(x=>x.id===(b.dataset.open||b.dataset.gate));if(t){showGate(t);if(b.dataset.open)openTask(t)}});const fresh=S.tasks.find(t=>!prev.has(t.id));if(fresh){showGate(fresh);await notify(fresh);if(fresh.action_url)openTask(fresh).catch(()=>{})}const j=await br("list_browser_jobs",{limit:20});$("#jobs").innerHTML=(j.jobs||[]).map(x=>'<div class="job"><b>'+esc(x.objective||x.platform_key||x.id)+'</b><small>'+esc(x.state)+' · '+esc(x.current_url||"")+'</small><div>'+esc(x.blocker||x.next_action||"")+'</div></div>').join("")||'<div class="muted">لا توجد Browser Jobs.</div>'}catch(e){if(S.token)$("#tasks").innerHTML='<div class="task error">'+esc(e.message)+'</div>'}}
async function run(planOnly){const p=$("#agent-prompt").value.trim();if(!p)return;try{log("MIDAD يعمل على المهمة…","agent");const d=await ai("plan",{prompt:p,execute:!planOnly,context:{app:"midad-omni-agent",profile:S.profile}});$("#recipe-output").textContent=JSON.stringify(d.plan||d,null,2);log(planOnly?"الخطة جاهزة":"أُرسلت المهمة إلى MIDAD","agent");if(!planOnly)view("missions")}catch(e){log(e.message,"error")}}
async function recipe(){const p=$("#automation-prompt").value.trim();if(!p)return;try{const d=await ai("automation_plan",{prompt:p});$("#recipe-output").textContent=JSON.stringify(d.plan||d,null,2);log("تم توليد Recipe آمنة","automation")}catch(e){log(e.message,"error")}}
function saveRecipe(){try{const r=JSON.parse($("#recipe-output").textContent);S.recipes.unshift({at:new Date().toISOString(),recipe:r});S.recipes=S.recipes.slice(0,30);localStorage.setItem("midad.omni.recipes",JSON.stringify(S.recipes));renderRecipes()}catch{}}
function renderRecipes(){$("#recipes").innerHTML=S.recipes.map(x=>'<div class="recipe"><b>'+esc(x.recipe?.title||"Recipe")+'</b><small>'+new Date(x.at).toLocaleString("ar")+'</small></div>').join("")||'<div class="muted">لا توجد Recipes.</div>}
function filePick(f){if(!f||!f.type.startsWith("image/"))return;const r=new FileReader();r.onload=()=>{S.file={name:f.name,type:f.type,dataUrl:r.result};$("#file-meta").textContent=f.name;$("#image-preview").src=r.result;$("#image-preview").style.display="block";log("تم اختيار ملف من الهاتف","files")};r.readAsDataURL(f)}
async function imageGen(){const p=$("#image-prompt").value.trim();if(!p)return;try{const d=await ai("gemini_image",{prompt:p,reference_image:S.file?.dataUrl||null,model:"gemini-3-pro-image"});if(d.image_data){const s="data:"+(d.mime_type||"image/png")+";base64,"+d.image_data;$("#image-preview").src=s;$("#image-preview").style.display="block";S.file={name:"midad-generated.png",type:d.mime_type||"image/png",dataUrl:s}}log("تم إنشاء/تحرير الصورة عبر Gemini","media")}catch(e){log(e.message,"error")}}
function profileLoad(){const p=S.profile;$("#profile-name").value=p.name||"";$("#profile-role").value=p.role||"";$("#profile-bio").value=p.bio||"";$("#profile-skills").value=p.skills||"";$("#profile-status").innerHTML="<b>Profile Context</b><p class=\"muted\">"+esc(JSON.stringify(p))+"</p>"}
function profileSave(){S.profile={...S.profile,name:$("#profile-name").value.trim(),role:$("#profile-role").value.trim(),bio:$("#profile-bio").value.trim(),skills:$("#profile-skills").value.trim(),updated_at:new Date().toISOString()};localStorage.setItem("midad.omni.profile",JSON.stringify(S.profile));profileLoad();log("تم حفظ Profile Context","profile")}
function pair(){const c=prompt("أدخل رمز الربط الظاهر في Control Room:");if(!c)return;post(CFG.b,{action:"pair_complete",code:c.toUpperCase(),device_id:"omni-"+crypto.randomUUID(),device_name:"MIDAD Omni Agent"}).then(d=>{S.token=d.bridge_token;localStorage.setItem("midad.omni.token",S.token);updatePair();refresh()}).catch(e=>alert(e.message))}
function updatePair(){const p=$("#pair-state");p.textContent=S.token?"MIDAD CONNECTED":"غير مقترن";p.className="pill "+(S.token?"ok":"warn")}
function nav(){ $$("[data-view]").forEach(b=>b.onclick=()=>view(b.dataset.view));$("#settings-btn").onclick=()=>view("settings");$("#run-agent").onclick=()=>run(false);$("#plan-agent").onclick=()=>run(true);$("#voice-btn")?.addEventListener("click",()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return log("الإدخال الصوتي غير مدعوم هنا","voice");const r=new R();r.lang="ar-SA";r.onresult=e=>{$("#agent-prompt").value=e.results[0][0].transcript;log("تم تحويل الصوت إلى أمر","voice")};r.start()});$("#notebook-btn")?.addEventListener("click",()=>window.open("https://notebooklm.google.com/","_blank"));$("#refresh-tasks").onclick=refresh;$("#refresh-jobs").onclick=refresh;$("#pair-device").onclick=pair;$("#generate-recipe").onclick=recipe;$("#save-recipe").onclick=saveRecipe;$("#pick-file").onclick=()=>$("#file-input").click();$("#file-input").onchange=e=>filePick(e.target.files?.[0]);$("#generate-image").onclick=imageGen;$("#use-profile").onclick=()=>{if(S.file?.dataUrl){S.profile.avatar_data_url=S.file.dataUrl;profileSave()}};$("#save-profile").onclick=profileSave;$("#clear-log").onclick=()=>$("#events").innerHTML="";$("#save-settings").onclick=()=>{CFG.b=$("#bridge-url").value.trim();CFG.a=$("#ai-url").value.trim();localStorage.setItem("midad.bridgeUrl",CFG.b);localStorage.setItem("midad.aiUrl",CFG.a)};$("#open-browser").onclick=()=>openTask({title:"Browser Task",action_url:$("#browser-url").value.trim()});$("#inspect-browser").onclick=()=>log("افتح صفحة داخل MIDAD أولًا للفحص","browser");$("#open-gemini").onclick=()=>window.open("https://gemini.google.com/","_blank");$("#open-notebook").onclick=()=>window.open("https://notebooklm.google.com/","_blank");$("#request-connection").onclick=async()=>{try{const d=await br("create_connection_request",{provider_name:$("#conn-provider").value.trim(),kind:$("#conn-kind").value,target_url:$("#conn-url").value.trim()});log("تم إنشاء طلب الربط: "+d.task.id,"connection");view("missions");refresh()}catch(e){log(e.message,"error")}}}
overlay();nav();updatePair();profileLoad();renderRecipes();log("MIDAD Omni Agent v0.2 · Native primary · Gemini specialist · TinyFish fallback","boot");if(S.token)refresh();setInterval(()=>S.token&&refresh(),12000);try{const b=B();b?.addListener?.("urlChangeEvent",e=>log("Browser: "+e.url,"browser"));b?.addListener?.("closeEvent",()=>{S.wid=null;log("تم إغلاق صفحة التدخل؛ المهمة محفوظة","browser")})}catch{}
})()