(() => {
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const CONFIG={bridgeUrl:localStorage.getItem("midad.bridgeUrl")||$("#bridge-url").value,aiUrl:localStorage.getItem("midad.aiUrl")||$("#ai-url").value};
let state={token:localStorage.getItem("midad.omni.token")||"",file:null,recipes:JSON.parse(localStorage.getItem("midad.omni.recipes")||"[]"),profile:JSON.parse(localStorage.getItem("midad.omni.profile")||"{}")};
function log(msg,type="info"){const el=document.createElement("div");el.className="task";el.innerHTML="<b>"+escapeHtml(msg)+"</b><small>"+new Date().toLocaleTimeString()+" · "+type+"</small>";$("#events").prepend(el)}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));}
async function post(url,body,headers={}){const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json",...headers},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch{}if(!r.ok||d.ok===false)throw new Error(d.error||("HTTP "+r.status));return d}
function view(id){$$(".view").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");$$(".bottom-nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===id));if(id==="missions")refreshMissions();}
async function bridge(action,body={}){if(!state.token)throw new Error("الهاتف غير مقترن بـMIDAD");return post(CONFIG.bridgeUrl,{action,...body},{"x-midad-bridge-token":state.token})}
async function ai(action,body={}){return post(CONFIG.aiUrl,{action,...body},{"x-midad-bridge-token":state.token})}
function updatePair(){const p=$("#pair-state");p.textContent=state.token?"مقترن مع MIDAD":"غير مقترن";p.className="pill "+(state.token?"":"warn")}
async function refreshMissions(){try{const d=await bridge("list_tasks",{limit:30});$("#task-count").textContent=(d.tasks||[]).length;$("#tasks").innerHTML=(d.tasks||[]).map(t=>'<div class="task"><b>'+escapeHtml(t.title)+'</b><small>Risk: '+escapeHtml(t.risk_class)+' · '+escapeHtml(t.status)+'</small><p>'+escapeHtml(t.instruction||t.reason||"")+'</p><div class="task-actions">'+(t.action_url?'<button class="secondary" data-open="'+escapeHtml(t.action_url)+'">فتح</button>':'')+'<button class="primary" data-complete="'+escapeHtml(t.id)+'">إكمال</button></div></div>').join("")||'<div class="panel muted">لا توجد مهام بشرية معلقة.</div>';$$("[data-open]").forEach(b=>b.onclick=()=>openSafe(b.dataset.open));$$("[data-complete]").forEach(b=>b.onclick=async()=>{try{await bridge("complete_task",{task_id:b.dataset.complete,response_data:{completed_from:"midad-omni-agent"}});log("تمت البوابة البشرية واستُؤنفت المهمة","human_gate");await refreshMissions()}catch(e){log(e.message,"error")}});const j=await bridge("list_browser_jobs",{limit:20});$("#jobs").innerHTML=(j.jobs||[]).map(x=>'<div class="job"><b>'+escapeHtml(x.objective||x.platform_key||x.id)+'</b><small>'+escapeHtml(x.state)+' · '+escapeHtml(x.current_url||"")+'</small><div>'+escapeHtml(x.blocker||x.next_action||"")+'</div></div>').join("")||'<div class="muted">لا توجد Browser Jobs.</div>'; }catch(e){$("#tasks").innerHTML='<div class="panel error">'+escapeHtml(e.message)+'</div>';}}
async function openSafe(url){if(!/^https:\/\//i.test(url))return log("تم حظر رابط غير HTTPS","safety");try{const B=window.Capacitor?.Plugins?.Browser;if(B?.open)await B.open({url});else window.open(url,"_blank","noopener,noreferrer")}catch{window.open(url,"_blank","noopener,noreferrer")}}
function localDeviceId(){let x=localStorage.getItem("midad.omni.deviceId");if(!x){x="omni-"+crypto.randomUUID();localStorage.setItem("midad.omni.deviceId",x)}return x}
async function pair(){const code=prompt("أدخل كود الربط لمرة واحدة الظاهر في MIDAD Control Room (10 دقائق):");if(!code)return;try{const d=await post(CONFIG.bridgeUrl,{action:"pair_complete",code:code.toUpperCase(),device_id:localDeviceId(),device_name:"MIDAD Omni Agent"});state.token=d.bridge_token;localStorage.setItem("midad.omni.token",state.token);updatePair();log("تم ربط الهاتف بنجاح","pairing");await refreshMissions()}catch(e){alert(e.message)}}
async function runAgent(planOnly=false){const prompt=$("#agent-prompt").value.trim();if(!prompt)return;try{log("بدء التحليل الهجين…","agent");const d=await ai("plan",{prompt,execute:!planOnly,context:{profile:state.profile,app:"midad-omni-agent"}});$("#recipe-output").textContent=JSON.stringify(d.plan||d,null,2);log(planOnly?"تم توليد الخطة دون تنفيذ":"تم إرسال المهمة إلى مسار MIDAD","agent");if(!planOnly)view("missions")}catch(e){log(e.message,"error")}}
async function generateRecipe(){const prompt=$("#automation-prompt").value.trim();if(!prompt)return;try{const d=await ai("automation_plan",{prompt,allowlist:["navigate","click","type_non_secret","select","wait","extract_public_text","screenshot","human_gate","verify"]});$("#recipe-output").textContent=JSON.stringify(d.plan||d,null,2)}catch(e){$("#recipe-output").textContent=JSON.stringify({error:e.message},null,2)}}
function saveRecipe(){try{const r=JSON.parse($("#recipe-output").textContent);state.recipes.unshift({id:crypto.randomUUID(),created_at:new Date().toISOString(),recipe:r});state.recipes=state.recipes.slice(0,30);localStorage.setItem("midad.omni.recipes",JSON.stringify(state.recipes));renderRecipes();log("تم حفظ Recipe محليًا","automation")}catch{}}
function renderRecipes(){$("#recipes").innerHTML=state.recipes.map(r=>'<div class="recipe"><b>'+escapeHtml(r.recipe?.title||"Recipe")+'</b><small>'+new Date(r.created_at).toLocaleString()+"</small></div>").join("")||'<div class="muted">لا توجد Recipes محفوظة.</div>'}
function loadProfile(){const p=state.profile;$("#profile-name").value=p.name||"";$("#profile-role").value=p.role||"";$("#profile-bio").value=p.bio||"";$("#profile-skills").value=p.skills||"";$("#profile-status").innerHTML='<b>Local Profile Context</b><p class="muted">'+escapeHtml(JSON.stringify(p))+'</p>'}
function saveProfile(){state.profile={name:$("#profile-name").value.trim(),role:$("#profile-role").value.trim(),bio:$("#profile-bio").value.trim(),skills:$("#profile-skills").value.trim(),updated_at:new Date().toISOString()};localStorage.setItem("midad.omni.profile",JSON.stringify(state.profile));loadProfile();log("تم تحديث Profile Context","profile")}
async function generateImage(){const prompt=$("#image-prompt").value.trim();if(!prompt)return;try{const d=await ai("gemini_image",{prompt,reference_image:state.file?.dataUrl||null});if(d.image_data){const src="data:"+(d.mime_type||"image/png")+";base64,"+d.image_data;$("#image-preview").src=src;$("#image-preview").style.display="block"}log("تم طلب توليد/تحرير الصورة عبر Gemini","media")}catch(e){log(e.message,"error")}}
async function filePicked(f){if(!f||!f.type.startsWith("image/"))return;const reader=new FileReader();reader.onload=()=>{state.file={name:f.name,type:f.type,size:f.size,dataUrl:reader.result};$("#file-meta").textContent=f.name+" · "+Math.round(f.size/1024)+" KB";$("#image-preview").src=reader.result;$("#image-preview").style.display="block";log("تم اختيار صورة من الهاتف","files")};reader.readAsDataURL(f)}
$$(".bottom-nav button").forEach(b=>b.onclick=()=>view(b.dataset.view));$("#settings-btn").onclick=()=>view("settings");$("#run-agent").onclick=()=>runAgent(false);$("#plan-agent").onclick=()=>runAgent(true);$("#refresh-tasks").onclick=refreshMissions;$("#refresh-jobs").onclick=refreshMissions;$("#open-browser").onclick=()=>openSafe($("#browser-url").value.trim());$("#inspect-browser").onclick=()=>log("Page Inspector: سيُسلّم DOM/visual context إلى Agent Kernel عند توفر Browser Worker","browser");$("#generate-recipe").onclick=generateRecipe;$("#save-recipe").onclick=saveRecipe;$("#pick-file").onclick=()=>$("#file-input").click();$("#file-input").onchange=e=>filePicked(e.target.files?.[0]);$("#generate-image").onclick=generateImage;$("#use-profile").onclick=()=>{if(state.file?.dataUrl){state.profile.avatar_data_url=state.file.dataUrl;localStorage.setItem("midad.omni.profile",JSON.stringify(state.profile));loadProfile();log("تم تعيين الصورة كـProfile Avatar محليًا","profile")}};$("#save-profile").onclick=saveProfile;$("#pair-device").onclick=pair;$("#save-settings").onclick=()=>{localStorage.setItem("midad.bridgeUrl",$("#bridge-url").value.trim());localStorage.setItem("midad.aiUrl",$("#ai-url").value.trim());CONFIG.bridgeUrl=$("#bridge-url").value.trim();CONFIG.aiUrl=$("#ai-url").value.trim();log("تم حفظ إعدادات الاتصال","settings")};$("#clear-log").onclick=()=>$("#events").innerHTML="";$("#notebook-btn").onclick=()=>openSafe("https://notebooklm.google.com/");$("#open-notebook").onclick=()=>openSafe("https://notebooklm.google.com/");$("#open-gemini").onclick=()=>openSafe("https://gemini.google.com/");$("#request-connection").onclick=async()=>{try{const d=await bridge("create_connection_request",{provider_name:$("#conn-provider").value.trim(),kind:$("#conn-kind").value,target_url:$("#conn-url").value.trim()});log("تم إنشاء طلب ربط بشري: "+d.task.id,"connection");view("missions")}catch(e){log(e.message,"error")}};$$("[data-k]").forEach(b=>b.onclick=()=>{$("#agent-prompt").value=b.dataset.k;view("command");log("تم تحميل قالب معرفة: "+b.dataset.k,"knowledge")});updatePair();loadProfile();renderRecipes();log("MIDAD Omni Agent جاهز — Native primary / TinyFish fallback","boot");if(state.token)refreshMissions();
})();