import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*","access-control-allow-methods":"POST,OPTIONS","access-control-allow-headers":"content-type,x-midad-bridge-token"};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const clip=(v:any,n=20000)=>String(v??"").trim().slice(0,n);
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,"0")).join("")}
async function session(sb:any,raw:string){const {data}=await sb.from("midad_human_bridge_sessions").select("id,owner_user_id,status,expires_at").eq("token_hash",await sha(raw)).maybeSingle();if(!data||data.status!=="ACTIVE"||new Date(data.expires_at).getTime()<=Date.now())return null;await sb.from("midad_human_bridge_sessions").update({last_seen_at:new Date().toISOString()}).eq("id",data.id);return data}
async function native(prompt:string,context:any){const url=Deno.env.get("SUPABASE_URL")||"",sk=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",ik=Deno.env.get("MIDAD_INGEST_KEY")||"";if(!url||!sk||!ik)return {ok:false,error:"native_unavailable"};const r=await fetch(url+"/functions/v1/midad_orchestrator",{method:"POST",headers:{"content-type":"application/json","authorization":"Bearer "+sk,"x-midad-ingest-key":ik},body:JSON.stringify({task:prompt,role:"reasoning",context})});const t=await r.text();let d:any={};try{d=JSON.parse(t)}catch{d={raw:t}};return r.ok&&d.success?{ok:true,output:d.final||"",model:d.selected_model||null,run_id:d.run_id}: {ok:false,error:"native_failed",detail:d}}
async function gemini(input:any,model="gemini-3.8-flash",tools:any[]=[],generation_config:any={thinking_level:"medium",thinking_summaries:"auto"}){const key=Deno.env.get("GEMINI_API_KEY")||"";if(!key)return {ok:false,error:"gemini_not_configured"};const r=await fetch("https://generativelanguage.googleapis.com/v1beta/interactions",{method:"POST",headers:{"content-type":"application/json","x-goog-api-key":key},body:JSON.stringify({model,input,tools:tools.length?tools:undefined,generation_config})});const d=await r.json().catch(()=>({}));return r.ok?{ok:true,data:d}:{ok:false,error:"gemini_failed",status:r.status,detail:d}}
function outText(d:any){if(d?.output_text)return String(d.output_text);for(const s of (d?.steps||[]).slice().reverse())for(const c of (s?.content||[]))if((c?.type==="text"||c?.type==="output_text")&&c?.text)return String(c.text);return ""}
function outImage(d:any){if(d?.output_image?.data)return d.output_image;for(const s of (d?.steps||[]).slice().reverse())for(const c of (s?.content||[]))if(c?.type==="image"&&c?.data)return c;return null}
function input(prompt:string,images:any[]=[]){const a:any[]=[{type:"text",text:clip(prompt,18000)}];for(const i of images.slice(0,4))if(i?.data&&i?.mime_type)a.push({type:"image",data:clip(i.data,8000000),mime_type:clip(i.mime_type,80)});return a}
const SYS="MIDAD Omni Agent: high-reliability agentic planner. Prefer MIDAD Native orchestration; use specialized Gemini capability when useful. Never bypass authentication, human verification, identity checks or signatures. Never collect recovery secrets. Explain gates, evidence, expected result and fallback.";
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return json({ok:false,error:"method_not_allowed"},405);
const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"");const body=await req.json().catch(()=>({}));const action=clip(body.action||"capabilities",80).toLowerCase();
try{
if(action==="capabilities")return json({ok:true,service:"midad_omni_agent_gateway",version:2,primary:"midad-native",specialists:["gemini","gemini-notebook"],fallbacks:["tinyfish"],capabilities:["plan","automation_plan","gemini_text","gemini_image","research","vision_inspect","notebook_route","human_intervention"],secrets:"server-side-only"});
if(action==="notebook_route")return json({ok:true,provider:"gemini-notebook",mode:"official-ui-handoff",url:"https://notebooklm.google.com/",enterprise_api_ready:Boolean(Deno.env.get("GOOGLE_CLOUD_PROJECT"))});
const raw=clip(req.headers.get("x-midad-bridge-token")||body.bridge_token,500);const s=await session(sb,raw);if(!s)return json({ok:false,error:"bridge_session_invalid_or_expired"},401);
const prompt=clip(body.prompt,18000);if(["plan","automation_plan","communication","gemini_text","research","vision_inspect"].includes(action)&&!prompt)return json({ok:false,error:"prompt_required"},400);
if(action==="communication"){const target=clip(body.target_language||"en",32),source=clip(body.source_language||"auto",32),channel=clip(body.channel||"customer_support",64),role=clip(body.agent_role||"support",64),tone=clip(body.tone||"professional_warm",64),mode=clip(body.mode||"reply_translate",64);const spec=SYS+"\nAct as MIDAD Global Communication Agent. Understand the incoming message even when it is in another language. Produce a truthful, culturally appropriate professional draft for the requested target language. Keep the owner's real profile and known context only; do not invent facts, commitments, prices, dates, identities or approvals. Never send the message automatically. Return strict JSON with keys detected_language, internal_arabic_summary, intent, reply_target, reply_arabic, translation_arabic, confidence, risk_flags, send_readiness, next_action.\nSOURCE="+source+" TARGET="+target+" CHANNEL="+channel+" ROLE="+role+" TONE="+tone+" MODE="+mode+"\nOWNER_PROFILE="+JSON.stringify(body.profile||{})+"\nCONTEXTS="+JSON.stringify(body.context||[])+"\nINCOMING:\n"+prompt;const n=await native(spec,{app:"midad-omni-agent",mode:"communication",target_language:target});if(n.ok)return json({ok:true,action,provider:"midad-native",output_text:n.output,result:parse(n.output),run_id:n.run_id,selected_model:n.model});const x=await gemini(input(spec),"gemini-3.8-flash",[],{thinking_level:"high",thinking_summaries:"auto"});return x.ok?json({ok:true,action,provider:"gemini",output_text:outText(x.data),result:parse(outText(x.data)),raw:x.data}):json(x,503)}if(action==="plan"){const n=await native(SYS+"\nPlan this user mission. Return JSON with title,intent,mode,steps,gates,evidence,expected_result,fallback. USER:\n"+prompt,{profile:body.context?.profile||{},app:"midad-omni-agent"});if(n.ok)return json({ok:true,action,provider:"midad-native",output_text:n.output,plan:parse(n.output),run_id:n.run_id,selected_model:n.model});}
if(action==="automation_plan"){const spec=SYS+"\nCreate an allowlisted Automation Recipe. Allowed step types: navigate,click,type_non_secret,select,wait,extract_public_text,screenshot,human_gate,verify. Never create secret-entry or bypass steps. Return JSON: title,steps,preconditions,expected_result,fallback. USER:\n"+prompt;const n=await native(spec,{app:"midad-omni-agent",mode:"automation_plan"});if(n.ok)return json({ok:true,action,provider:"midad-native",output_text:n.output,plan:parse(n.output),run_id:n.run_id,selected_model:n.model});}
const imgs=(body.images||[]).map((x:any)=>({data:x?.data,mime_type:x?.mime_type||x?.mimeType})).filter((x:any)=>x.data&&x.mime_type);
if(action==="vision_inspect"){const g=await gemini(input(SYS+"\nInspect this UI/image and identify visible fields, blockers and safe next steps. Do not infer hidden secrets.\n"+prompt,imgs),"gemini-3.8-flash",[],{thinking_level:"high",thinking_summaries:"auto"});return g.ok?json({ok:true,action,provider:"gemini",output_text:outText(g.data),raw:g.data}):json(g,503);}
if(action==="research")return (async()=>{const g=await gemini(input(SYS+"\nResearch this request using fresh web evidence. Return sources, confidence, caveats and next actions.\n"+prompt),"gemini-3.8-flash",[{type:"google_search"}],{thinking_level:"high",thinking_summaries:"auto"});return g.ok?json({ok:true,action,provider:"gemini",output_text:outText(g.data),raw:g.data}):json(g,503)})();
if(action==="gemini_text")return (async()=>{const g=await gemini(input(SYS+"\nAnswer the user's task with explicit assumptions and next actions.\n"+prompt,imgs),"gemini-3.8-flash",[],{thinking_level:clip(body.thinking_level,10)||"high",thinking_summaries:"auto"});return g.ok?json({ok:true,action,provider:"gemini",output_text:outText(g.data),raw:g.data}):json(g,503)})();
if(action==="gemini_image"){const ref=body.reference_image?String(body.reference_image):"";const m=ref.match(/^data:([^;]+);base64,(.+)$/s);const g=await gemini(input(prompt,m?[{data:m[2],mime_type:m[1]}]:[]),"gemini-3-pro-image",[],{});if(!g.ok)return json(g,503);const img=outImage(g.data);return img?json({ok:true,action,provider:"gemini",mime_type:img.mime_type||"image/png",image_data:img.data}):json({ok:false,error:"image_output_missing"},502)}
return json({ok:false,error:"unsupported_action"},400)}catch(e){return json({ok:false,error:String(e).slice(0,1600)},500)}
});
function parse(t:string){try{return JSON.parse(t)}catch{const a=t.indexOf("{"),b=t.lastIndexOf("}");if(a>=0&&b>a)try{return JSON.parse(t.slice(a,b+1))}catch{}return {raw:t}}}